'use strict';
app.factory('wordsService', [function () {

    var wordsServicefactory = {};

    var words = [["abotonar", "to button (up)"],
    ["el abrigo", "coat"],
    ["abrochar", "to fasten, befestigen"],
    ["la aguja", "needle"],
    ["el alfiler", "pin, stecknadel"],
    ["el algodón", "cotton"],
    ["anaranjado", "orange (color)"],
    ["ancho", "wide, big, loose(-fitting)"],
    ["el anillo", "ring"],
    ["apretado", "serré (vêtement)"],
    ["arreglar", "to mend, to repair"],
    ["áspero", "rough"],
    ["el bañador", "swimming/bathing costume, swimming trunks"],
    ["blando", "soft"],
    ["la blusa", "blouse"],
    ["el bolsillo", "pocket"],
    ["el bolso", "handbag"],
    ["la bota", "boot"],
    ["el botón", "button"],
    ["las bragas", "knickers, culotte"],
    ["la bufanda", "scarf"],
    ["el calcetín", "sock"],
    ["el calzado", "footwear, chaussure"],
    ["los calzoncillos", "le slip"],
    ["la camisa", "shirt"],
    ["la camiseta", "T-shirt/tee-shirt; vest"],
    ["el camisón", "nightdress"],
    ["la chaqueta", "jacket"],
    ["el cinturón", "belt"],
    ["el collar", "necklace"],
    ["cómodo", "comfortable"],
    ["la corbata", "tie; cravat(e)"],
    ["el cordón (de zapato)", "(shoe)lace"],
    ["la correa", "strap, la sangle"],
    ["corto", "short"],
    ["coser", "to sew (up/on)"],
    ["la cremallera", "zip, Reisverschluss"],
    ["el cuello", "le col"],
    ["el cuero", "leather"],
    ["desabotonar", "to unbutton"],
    ["desabrochar", "to unfasten (des boutons...)"],
    ["desnudarse", "to undress (oneself), to get undressed, to strip"],
    ["desnudo", "naked, bare, nude"],
    ["dorado", "gold (in colour), golden"],
    ["entallar", "to (be a good) fit"],
    ["la falda", "skirt, ja jupe"],
    ["el forro", "lining, doublure, Futter"],
    ["las gafas de sol", "sunglasses"],
    ["la gorra", "bonnet, mütze"],
    ["gris", "grey"],
    ["grueso", "thick; coarse"],
    ["el guante", "glove"],
    ["el hilo", "thread, Faden"],
    ["el impermeable", "raincoat, waterproof (coat)"],
    ["el jersey", "sweater, pullover, jumper"],
    ["las joyas", "jewellery, jewels"],
    ["la lana", "wool"],
    ["largo", "long"],
    ["la mancha", "stain, mark, spot"],
    ["la manga", "sleeve"],
    ["el maquillaje", "make-up"],
    ["la máquina de coser", "sewing machine"],
    ["marrón", "brown"],
    ["las medias", "stockings"],
    ["de moda", "fashionable"],
    ["el monedero", "purse, porte monnaie"],
    ["morado", "purple"],
    ["de oro", "gold, (made) of gold"],
    ["los pantalones", "trousers"],
    ["los pantalones cortos", "short trousers, shorts"],
    ["el pañuelo", "handkerchief; (head)scarf"],
    ["el paraguas", "umbrella"],
    ["el pendiente", "earring"],
    ["el pijama", "(pair of) pyjamas"],
    ["de plata", "silver, (made) of silver"],
    ["plateado", "silver (in colour)"],
    ["ponerse", "to put on"],
    ["la prenda", "vêtement, article of clothing"],
    ["la pulsera", "bracelet"],
    ["quitar", "to take off, to remove"],
    ["rasgar", "to tear, to rip"],
    ["el reloj (de pulsera)", "(wrist)watch"],
    ["la ropa", "clothing, clothes"],
    ["la ropa interior", "underwear, underclothes"],
    ["la sandalia", "sandal"],
    ["la seda", "silk"],
    ["suave", "smooth"],
    ["el sujetador", "bra"],
    ["la talla", "size"],
    ["la tela", "cloth, fabric, material"],
    ["teñir", "teindre"],
    ["el terciopelo", "velvet, Samt, velours"],
    ["el traje", "(man's) suit"],
    ["los vaqueros", "jeans"],
    ["el velo", "veil"],
    ["el vestido", "(woman's) dress"],
    ["vestirse", "to dress (oneself), to get dressed"],
    ["la zapatilla", "slipper"],
    ["tacón (alto)", "(high) heels"],
    ["el abogado", "l'avocat (profession)"],
    ["el abuelo", "grandfather"],
    ["la actriz", "actress"],
    ["la adolescencia", "adolescence"],
    ["el adulto", "(male) adult"],
    ["agresivo", "aggressive"],
    ["alegre", "joyeux"],
    ["ambicioso", "ambitious"],
    ["los antepasados", "ancestors"],
    ["el apellido", "surname, last name"],
    ["el arquitecto", "(male) architect"],
    ["el bailarín", "(male) dancer"],
    ["el bibliotecario", "le bibliothéquaire"],
    ["la boda", "wedding, marriage"],
    ["el bombero", "fireman, fire-fighter"],
    ["el camarero", "waiter"],
    ["el camionero", "(male) lorry driver"],
    ["el/la cantante", "chanteur"],
    ["el cartero", "postman"],
    ["el científico", "scientist"],
    ["el cirujano", "(male) surgeon"],
    ["el cocinero", "(male) cook"],
    ["compadecer", "to pity, to be sorry for"],
    ["el compositor", "(male) composer"],
    ["el constructor", "(male) builder"],
    ["el/la contable", "le comptable"],
    ["el/la cónyuge", "spouse, partner"],
    ["débil", "weak"],
    ["el/la dentista", "dentist"],
    ["el dependiente", "(male) shop/sales assistant"],
    ["deprimirse", "to become/get depressed"],
    ["despreciar", "mépriser "],
    ["el diplomático", "(male) diplomat"],
    ["la dirección", "address"],
    ["la edad", "age"],
    ["egoísta", "selfish"],
    ["el/la electricista", "electrician"],
    ["el/la espía", "spy"],
    ["enamorarse (de)", "to fall in love (with)"],
    ["el enfermero", "(male) nurse"],
    ["envidioso", "envious; jealous"],
    ["el escritor", "(male) writer"],
    ["la estrella de cine", "film/movie star"],
    ["estúpido", "stupide"],
    ["la fecha de nacimiento", "date of birth"],
    ["felicitar", "to compliment"],
    ["feo", "ugly"],
    ["el fotógrafo", "(male) photographer"],
    ["??", "fonctionnaire"],
    ["el granjero", "(male) farmer"],
    ["la hijastra", "stepdaughter"],
    ["el hijastro", "stepson"],
    ["el hombre de negocios", "businessman"],
    ["el ingeniero", "(male) engineer"],
    ["el jardinero", "(male) gardener"],
    ["jubilarse", "to retire"],
    ["el/la juez", "judge"],
    ["la madrastra", "stepmother"],
    ["el marido", "husband"],
    ["el matrimonio", "marriage, matrimony"],
    ["el mecánico", "(male) mechanic"],
    ["el médico", "(male) doctor"],
    ["el minero", "(male) miner"],
    ["el/la músico", "musician"],
    ["nacer", "to be born"],
    ["el nacimiento", "birth"],
    ["nervioso", "nervous; highly-strung; restless"],
    ["el nieto", "grandson"],
    ["los nietos", "grandchildren"],
    ["la niñez", "childhood"],
    ["el niño", "(little) boy"],
    ["el novio", "boyfriend"],
    ["la nuera", "daughter-in-law"],
    ["el número de teléfono", "telephone number"],
    ["odiar", "to hate"],
    ["orgulloso", "proud; haughty"],
    ["el padrastro", "stepfather"],
    ["los padres", "parents"],
    ["el/la pariente", "relative/relation"],
    ["el peluquero", "(male) hairdresser"],
    ["perdonar", "to forgive"],
    ["el/la periodista", "journalist"],
    ["el pescador", "fisherman"],
    ["el/la piloto", "pilot"],
    ["el pintor", "(male) painter"],
    ["el/la policía", "policeman/policewoman"],
    ["el/la político", "politician"],
    ["presentar (a)", "to introduce (to)"],
    ["la prima", "(female) cousin"],
    ["reconocer", "to recognize"],
    ["rencoroso", "rancunier"],
    ["el secretario", "(male) secretary"],
    ["el/la soldado", "soldier"],
    ["la suegra", "mother-in-law"],
    ["el suegro", "father-in-law"],
    ["el/la taxista", "taxi driver"],
    ["tímido", "shy, timid"],
    ["el tío", "uncle"],
    ["el yerno", "son-in-law"],
    ["el aceite", "oil"],
    ["agrio", "sour"],
    ["el ajo", "garlic"],
    ["el albaricoque", "apricot"],
    ["el aliño", "dressing de salade"],
    ["almorzar", "to (have) lunch"],
    ["amargo", "bitter"],
    ["el apio", "celery"],
    ["asar", "to roast"],
    ["el azúcar", "sugar"],
    ["la bebida", "drink, beverage"],
    ["la berenjena", "aubergine"],
    ["la cacerola", "casserole"],
    ["el caldo", "stock; (thin) soup"],
    ["caliente", "warm, hot"],
    ["la carne", "meat"],
    ["la carta", "menu"],
    ["la cebolla", "onion"],
    ["la cena", "dinner, supper, evening meal"],
    ["el cerdo", "pork"],
    ["la cereza", "cherry"],
    ["el champiñón", "mushroom"],
    ["la ciruela", "plum, prune"],
    ["la col", "cabbage"],
    ["la coliflor", "cauliflower"],
    ["el condimento", "seasoning, flavouring, condiment"],
    ["congelado", "frozen"],
    ["el cordero", "lamb"],
    ["crudo", "raw"],
    ["los cubiertos", "cutlery"],
    ["la cuchara", "spoon"],
    ["el cuchillo", "knife"],
    ["la cuenta", "bill (in restaurant)"],
    ["desayunar", "to (have) breakfast"],
    ["el desayuno", "breakfast"],
    ["dulce", "sweet"],
    ["la ensalada", "salad"],
    ["la especia", "spice"],
    ["las espinacas", "spinach"],
    ["flojo", "weak (drink)"],
    ["la frambuesa", "framboise"],
    ["fregar los platos", "to wash up, to do the washing-up/dishes"],
    ["freír", "to fry"],
    ["la fresa", "fraise"],
    ["la galleta", "biscuit; cracker"],
    ["la gaseosa", "lemonade"],
    ["la grosella negra", "blackcurrant"],
    ["el guisante", "pea"],
    ["la harina", "flour"],
    ["hervir", "to boil"],
    ["la hierba", "herb"],
    ["el huevo", "egg"],
    ["la judía", "bean"],
    ["la lata", "tin, can"],
    ["la leche", "milk"],
    ["la lechuga", "lettuce"],
    ["el limón", "lemon"],
    ["el maíz", "maize, sweet corn"],
    ["la mantequilla", "butter"],
    ["la manzana", "apple"],
    ["el melocotón", "peach"],
    ["la mermelada", "jam; marmalade"],
    ["la miel", "honey"],
    ["la mostaza", "mustard"],
    ["muy hecho", "overdone; well done"],
    ["la naranja", "orange (fruit)"],
    ["la nata", "cream (culinaire)"],
    ["la nuez", "nut; walnut"],
    ["oler", "to smell"],
    ["pasado", "old; stale, bad; overripe"],
    ["el pepino", "cucumber"],
    ["la pera", "pear"],
    ["el pescado", "fish"],
    ["la pimienta", "pepper (spice)"],
    ["el pimiento", "pepper (vegetable)"],
    ["la piña", "pineapple"],
    ["el platillo", "untertasse, saucer"],
    ["el plato principal", "main course"],
    ["poco hecho", "underdone; rare"],
    ["podrido", "rotten, pourri"],
    ["el pomelo", "grapefruit"],
    ["poner la mesa", "to set/lay the table"],
    ["el postre", "dessert"],
    ["el puerro", "leek"],
    ["recoger la mesa", "to clear the table"],
    ["la remolacha", "beetroot"],
    ["sabroso", "savoureux"],
    ["la sal", "salt"],
    ["salado (adj.)", "salty, salted"],
    ["la salchicha", "sausage"],
    ["la sartén", "frying pan"],
    ["la sidra", "cider"],
    ["el tarro", "pot, bocal"],
    ["la taza", "cup, mug"],
    ["el té", "tea"],
    ["el tenedor", "fork"],
    ["tener hambre", "to be hungry"],
    ["tierno", "tender, soft"],
    ["tomar un bocado", "to have a bite to eat, to have a snack"],
    ["el tomate", "tomato"],
    ["el trigo", "le blé"],
    ["la uva", "le raisin"],
    ["la uva pasa", "raisin sec"],
    ["el vaso", "glass, tumbler"],
    ["las verduras", "greens, (cooked) vegetables"],
    ["el vinagre", "vinegar"],
    ["la zanahoria", "carrot"],
    ["el zumo", "juice"],
    ["abajo", "downstairs"],
    ["acostarse", "to go to bed; to lie down"],
    ["el alféizar", "window sill"],
    ["la alfombra", "le tapis"],
    ["la almohada", "oreiller"],
    ["amplio", "spacious, roomy"],
    ["apagar", "to turn/switch off"],
    ["el aparador", "sideboard, vitrine"],
    ["el armario", "wardrobe, cupboard"],
    ["arriba", "upstairs"],
    ["el balcón", "balcony"],
    ["bañarse", "to have/take a bath"],
    ["el baño", "bathroom"],
    ["ir al baño", "to go to the toilet"],
    ["barrer", "to sweep"],
    ["el cajón", "drawer"],
    ["la calefacción central", "central heating"],
    ["el calentador", "heater"],
    ["en casa", "at home"],
    ["cepillarse los dientes", "to brush one's teeth"],
    ["el cepillo", "brosse (cheveux, ongles, dents)"],
    ["la cera", "wax"],
    ["la cerradura", "lock, das Schloss"],
    ["cerrar", "to close, to shut"],
    ["cerrar la puerta con llave", "to lock the door (with key)"],
    ["el césped", "lawn, grass"],
    ["el champú", "shampoo"],
    ["la chimenea", "chimney; fireplace"],
    ["el cojín", "cushion"],
    ["el comedor", "dining room"],
    ["la cómoda", "chest of drawers"],
    ["cómodo", "comfortable"],
    ["el congelador", "freezer"],
    ["construir", "to build, to construct"],
    ["la contraventana", "shutter"],
    ["correr las cortinas", "to close/draw the curtains"],
    ["la cortina", "rideau"],
    ["el cuadro", "picture, painting"],
    ["el cuarto", "room"],
    ["el cubo", "bucket"],
    ["el cubo de la basura", "la poubelle"],
    ["dentro", "inside; indoors"],
    ["descorrer las cortinas", "to open/draw the curtains"],
    ["desordenado", "untidy"],
    ["el despacho", "le bureau"],
    ["el despertador", "alarm clock"],
    ["despertarse", "to wake up"],
    ["dormirse", "to go to sleep; to fall asleep"],
    ["el dormitorio", "bedroom"],
    ["la ducha", "shower"],
    ["ducharse", "to have/take a shower"],
    ["encender", "to turn/switch on"],
    ["el enchufe", "plug; (electric) socket, power point"],
    ["la escalera", "staircase, stairs"],
    ["la escoba", "broom, brush"],
    ["el escritorio", "(writing) desk"],
    ["el espejo", "mirror"],
    ["el estante", "shelf"],
    ["la estantería", "bookcase, shelves"],
    ["el fregadero", "(kitchen) sink"],
    ["la fregona", "mop"],
    ["fuera", "outside"],
    ["hacer la cama", "to make the bed"],
    ["hacer la colada", "to do the washing/laundry"],
    ["el horno", "oven"],
    ["el horno microondas", "microwave (oven)"],
    ["el interruptor", "switch, der Schalter"],
    ["el jabón", "soap; bar of soap"],
    ["la lavadora", "washing machine"],
    ["el lavavajillas", "dishwasher"],
    ["levantarse", "to get up, to rise"],
    ["limpiar", "nettoyer"],
    ["limpio", "clean"],
    ["la llave", "key"],
    ["la manta", "couverture"],
    ["los muebles", "furniture"],
    ["el muro", "(exterior) wall"],
    ["la nevera", "fridge, refrigerator"],
    ["ordenado", "tidy"],
    ["oscuro", "dark; dim, gloomy"],
    ["la pared", "(interior) wall"],
    ["la pasta de dientes", "toothpaste"],
    ["peinarse", "to comb one's hair"],
    ["la persiana", "(Venetian) blind"],
    ["pintar", "to paint"],
    ["la plancha", "iron, bügeleisen"],
    ["planchar", "to iron; to do the ironing"],
    ["el polvo", "dust"],
    ["polvoriento", "dusty"],
    ["la radio", "radio"],
    ["reparar", "to repair"],
    ["la sábana", "sheet"],
    ["la sala (de estar)", "living/sitting room, lounge"],
    ["la silla", "chair"],
    ["el sillón", "le fauteuil"],
    ["el sofá", "sofa, settee"],
    ["la suciedad", "dirt, grime"],
    ["sucio", "dirty, grimy"],
    ["el suelo", "le sol, the floor"],
    ["el techo", "ceiling"],
    ["el tejado", "roof"],
    ["la televisión", "television"],
    ["tender la colada", "to hang out/up the washing/laundry"],
    ["la toalla", "towel"],
    ["el tocador", "boudoir, coiffeuse"],
    ["el trapo", "cloth, rag"],
    ["el váter", "toilet, lavatory"],
    ["la ventana", "window"],
    ["actuar", "to act, to perform"],
    ["agradable", "pleasant, nice, agreeable"],
    ["el ajedrez", "chess"],
    ["aplaudir", "to applaud, to clap"],
    ["el árbitro", "l'arbitre"],
    ["el arte", "art"],
    ["el atletismo", "athletics"],
    ["el auditorio", "audience, public"],
    ["el ballet", "ballet"],
    ["el balón", "le balon"],
    ["la banda", "(brass) band"],
    ["la baraja", "pack/deck (of cards)"],
    ["la batería", "drums, drum kit"],
    ["el billar americano", "le billard"],
    ["el boxeo", "boxing"],
    ["el campeonato", "championship"],
    ["el canal (de televisión)", "(television) channel"],
    ["la canción", "song"],
    ["el capítulo", "chapter"],
    ["la ciencia-ficción", "science fiction"],
    ["el clarinete", "clarinet"],
    ["la comedia", "comedy; play, drama"],
    ["el concierto", "concert; concerto"],
    ["el coro", "choir, chorus"],
    ["el crucigrama", "crossword"],
    ["el cuento", "le conte, la nouvelle"],
    ["el deporte", "sport"],
    ["desagradable", "unpleasant, disagreeable"],
    ["el descanso", "la pause, le break"],
    ["dibujar", "to draw"],
    ["el dibujo", "le dessin"],
    ["divertido", "amusing, entertaining"],
    ["divertir", "to amuse, to entertain"],
    ["divertirse", "to amuse/enjoy oneself, to have fun"],
    ["el documental", "documentary"],
    ["echar los dados", "to throw the dice"],
    ["la emisora (de radio)", "(radio) station"],
    ["emitir", "to broadcast"],
    ["emocionante", "excitant"],
    ["el empate", "draw, tie"],
    ["el ensayo general", "dress rehearsal"],
    ["el equipo", "team"],
    ["escalar una montaña", "to climb a mountain"],
    ["la escena", "stage; scene"],
    ["escuchar la radio", "to listen to the radio"],
    ["la escultura", "sculpture"],
    ["el espectáculo de variedades", "variety show"],
    ["el esquí", "le ski"],
    ["excelente", "excellent"],
    ["la exposición", "exhibition, show"],
    ["favorito", "favourite"],
    ["la flauta", "flute"],
    ["el fútbol", "football"],
    ["ganar", "to win"],
    ["la gimnasia", "gymnastics"],
    ["la guitarra", "guitar"],
    ["el/la hincha", "(football) fan/supporter"],
    ["improvisar", "to improvise"],
    ["el instrumento", "instrument"],
    ["ir a nadar", "to go swimming, to go for a swim"],
    ["el juego", "game; play, playing"],
    ["jugar a las cartas", "to play cards"],
    ["jugar al fútbol", "to play football"],
    ["el libro", "book"],
    ["el lienzo", "canvas"],
    ["marcar un gol", "to score a goal"],
    ["la música clásica", "classical music"],
    ["las noticias", "news"],
    ["la novela", "novel"],
    ["la novela policíaca", "detective story/novel"],
    ["la obra (dramática)", "la pièce (de théatre)"],
    ["la ópera", "opera"],
    ["la orquesta", "orchestra"],
    ["el partido de fútbol", "football match/game"],
    ["el pasatiempo", "pastime, hobby"],
    ["el patinaje", "skating"],
    ["la película", "film, movie"],
    ["la película de terror", "horror film/movie"],
    ["la pelota", "(small) ball"],
    ["el periódico", "newspaper"],
    ["el piano de cola", "grand piano"],
    ["pincel?", "le pinceau (artiste)"],
    ["pintar", "to paint"],
    ["la pintura", "painting"],
    ["el poema", "poem"],
    ["la poesía", "poetry"],
    ["el pop", "pop (music)"],
    ["el programa concurso", "game/quiz show"],
    ["el programa (de televisión)", "(television) programme"],
    ["la raqueta", "racket/racquet"],
    ["la representación", "la représentation, le spectacle"],
    ["el retrato", "portrait"],
    ["la revista", "la revue, journal"],
    ["el saxofón", "saxophone"],
    ["la serie (de televisión)", "(television) series/serial"],
    ["el tambor", "le tambour"],
    ["el tenis", "tennis"],
    ["el tiempo libre", "spare/free time"],
    ["el título", "title"],
    ["tocar de oído", "to play by ear"],
    ["tocar el piano", "to play the piano"],
    ["tocar la guitarra", "to play the guitar"],
    ["los toros", "bullfight; bullfighting"],
    ["la tragedia", "tragedy"],
    ["el trombón", "trombone"],
    ["la trompeta", "trumpet"],
    ["el truco de cartas", "card trick"],
    ["ver la televisión", "to watch television"],
    ["el violín", "violin"],
    ["el violonchelo", "cello"],
    ["resaca", "gueule de bois"],
    ["después (de)", "after, afterward"],
    ["ya", "already"],
    ["siempre", "always"],
    ["en cuanto", "as soon as"],
    ["al principio", "at first"],
    ["por fin", "at last"],
    ["al principio", "at the beginning"],
    ["al mismo tiempo", "at the same time"],
    ["inmediatamente", "at once"],
    ["antes de (que)", "before"],
    ["brevemente", "briefly"],
    ["antes de ayer, antier", "day before yesterday"],
    ["durante", "during"],
    ["eventualmente", "eventually"],
    ["finalmente, por fin", "finally"],
    ["primero", "first"],
    ["frecuentemente", "frequently"],
    ["inmediatamente", "immediately"],
    ["al rato", "in a little while"],
    ["en primer lugar", "in the first place"],
    ["mientras tanto", "in the meantime"],
    ["en el pasado/futuro", "in the past/future"],
    ["anoche", "last night"],
    ["luego", "later"],
    ["mientras tanto", "meanwhile"],
    ["la mayor parte del tiempo", "most of the time"],
    ["luego", "next"],
    ["al otro día", "(the) next day"],
    ["a la mañana", "(the) next morning"],
    ["antenoche", "night before last"],
    ["ahora", "now"],
    ["muchas veces, a menudo", "often"],
    ["al (día/mes/año) siguiente", "on the following day"],
    ["una vez", "once"],
    ["rápidamente", "promptly"],
    ["raramente", "rarely"],
    ["a veces, algunas veces", "sometimes"],
    ["pronto", "soon"],
    ["de repente, de golpe", "suddenly"],
    ["entonces", "then"],
    ["ayer", "yesterday"],
    ["encima de, arriba de", "above"],
    ["entre, en medio de", "among"],
    ["alrededor de", "around"],
    ["abajo", "below"],
    ["al lado de", "beside"],
    ["más allá, más lejos", "beyond"],
    ["abajo, hacia abajo", "down"],
    ["adelante", "forward"],
    ["de, desde", "from"],
    ["aquí", "here"],
    ["delante de", "in front of"],
    ["adentro", "inside"],
    ["cerca de", "nearby"],
    ["al lado de", "next to"],
    ["sobre", "on"],
    ["frente a", "opposite"],
    ["afuera", "outside"],
    ["por, através de", "through"],
    ["debajo de", "under"],
    ["otra vez", "again"],
    ["también", "also"],
    ["y", "and"],
    ["as así como", "as well"],
    ["además", "besides"],
    ["para mencionar una cosa", "for one thing"],
    ["además", "futher, furthermore"],
    ["además de", "in addittion to"],
    ["en primer lugar", "in the first place"],
    ["en segundo lugar", "in the second place"],
    ["por último", "last(ly)"],
    ["asimismo, igualmente, de mismo modo", "likewise"],
    ["más", "more"],
    ["además, es más, por otra parte", "moreover"],
    ["por otro lado", "on the other hand"],
    ["de igualmanera", "similarly 1"],
    ["semejantemente", "similarly 2"],
    ["entre ellos/ellas figura", "among them figure"],
    ["como sigue", "as follows"],
    ["por ejemplo, ejemplo de esto", "for example"],
    ["en otras palabras", "in other words"],
    ["en particular", "in particular"],
    ["en primer lugar", "in the first instance"],
    ["de la manera siguiente", "in the following way"],
    ["principalmente", "mainly"],
    ["es decir, a saber, o sea", "namely"],
    ["específicamente", "specifically"],
    ["como", "such as"],
    ["es decir", "that is"],
    ["asi", "thus"],
    ["para ilustrar", "to illustrate"],
    ["aunque", "although"],
    ["aún así, no obstante", "even so"],
    ["a la inversa, vice-versa", "conversely"],
    ["diferentemente, de manera diferente", "differently"],
    ["sin embargo, no obstante", "however"],
    ["en contraste, por el contrario", "in contrast"],
    ["a pesar de", "in spite of"],
    ["de cierta manera, hasta cierto punto, en cierto modo", "in a way"],
    ["sin embargo, no obstante, con todo, a pesar de eso", "cependant, nevertheless"],
    ["por un lado", "on the one hand"],
    ["por otro lado, por otra parte", "on the other hand"],
    ["sin duda", "no doubt"],
    ["por supuesto, claro está que", "of course"],
    ["al contrario", "on the contrary"],
    ["de otra manera, de otro modo", "otherwise"],
    ["por consiguiente, en conformidad con", "accordingly"],
    ["como resultado", "as a result"],
    ["como es/era de esperarse", "as one would expect"],
    ["en consecuencia", "consequently"],
    ["por esta razón", "for this reason"],
    ["por (lo) tanto, por esto", "hence"],
    ["en todo caso, de cualquier modo, de todas maneras", "in any case"],
    ["lógicamente", "logically"],
    ["por supuesto", "of course"],
    ["entonces, luego", "then"],
    ["por lo tanto, así que", "therefore"],
    ["así", "thus"],
    ["con que, así que", "so"],
    ["sigue que", "it follows that"],
    ["sobre todo", "above all"],
    ["igualmente", "equally"],
    ["especialmente", "especially"],
    ["efectivamente, realmente, en verdad, de veras, en realidad", "indeed"],
    ["de hecho", "in fact"],
    ["principalmente, por la mayor parte", "principally"],
    ["al fin y al cabo, después de todo", "after all"],
    ["como se ha notado", "as has been noted"],
    ["finalmente, por fin", "finally"],
    ["en efecto", "in effect"],
    ["en fin, en fin de cuentas", "in the end"],
    ["en otras palabras", "in other words"],
    ["en síntesis", "in sum"],
    ["en general, mirándolo todo", "on the whole"],
    ["para resumir, en resumen", "to summarize"],
    ["es decir, o sea", "that is"],
    ["la acera", "pavement"],
    ["los (grandes) almacenes", "department store"],
    ["ancho", "wide"],
    ["el aparcamiento", "car park"],
    ["el arco", "arch"],
    ["el ascensor", "lift"],
    ["el ayuntamiento", "town/city hall"],
    ["el billete (de banco)", "(bank)note"],
    ["de buena calidad", "(of) good/high quality"],
    ["el buzón", "postbox, pillar box"],
    ["la caja", "till, la caisse"],
    ["el cajero automático", "cash machine/dispenser"],
    ["el callejón", "alley, passage"],
    ["el callejón sin salida", "dead end, cul-de-sac, blind alley"],
    ["la carnicería", "butcher's (shop)"],
    ["la cesta", "basket"],
    ["el circo", "circus"],
    ["la comisaría", "police station"],
    ["concurrido", "busy, crowded"],
    ["el cruce", "junction, crossroads"],
    ["cruzar la calle", "to cross the street/road"],
    ["dar un paseo", "to go for a walk"],
    ["de baja calidad", "(of) poor/low quality"],
    ["de segunda mano", "second-hand"],
    ["el descuento", "the discount"],
    ["el edificio", "building"],
    ["el embotellamiento", "traffic jam"],
    ["la escalera mecánica", "escalator"],
    ["el escaparate", "(shop) window"],
    ["la esquina", "corner"],
    ["el estadio", "stadium"],
    ["la estatua", "statue"],
    ["estrecho", "narrow"],
    ["la farmacia", "la pharmacie"],
    ["la farola", "street lamp/light, lamppost"],
    ["la fuente", "fountain"],
    ["la ganga", "bargain, good buy"],
    ["girar a la derecha", "to turn right"],
    ["girar a la izquierda", "to turn left"],
    ["hacer cola", "to queue (up)"],
    ["hacer la compra", "to do the shopping"],
    ["ir de compras", "to go shopping"],
    ["la joyería", "jeweller's (shop), jewellery shop"],
    ["la juguetería", "toyshop"],
    ["la librería", "bookshop"],
    ["la mezquita", "mosque"],
    ["la moneda", "currency; coin"],
    ["el mostrador", "comptoir"],
    ["la oficina de correos", "post office"],
    ["pagar al contado", "to pay (in) cash"],
    ["la panadería", "baker's (shop), bakery"],
    ["el parque de bomberos", "fire station"],
    ["el paso de peatones", "pedestrian crossing"],
    ["el paso subterráneo", "underpass, subway"],
    ["la pastelería", "cake shop"],
    ["la peluquería", "hairdresser's, hair salon"],
    ["perderse", "to get lost, to lose one's way"],
    ["la pescadería", "fish shop, fishmonger's (shop)"],
    ["la planta baja", "ground floor"],
    ["el polideportivo", "sports/leisure centre"],
    ["el primer piso", "first floor"],
    ["el probador", "fitting/changing room"],
    ["probarse", "to try on"],
    ["el puente", "bridge"],
    ["el quiosco", "kiosk, (news) stand"],
    ["el recibo", "receipt"],
    ["el reembolso", "refund, reimbursement"],
    ["reunirse (con)", "to meet, to meet up (with)"],
    ["el semáforo", "(set of) traffic lights"],
    ["la señal (de tráfico)", "(road) sign"],
    ["los servicios", "toilet(s)"],
    ["la sinagoga", "synagogue"],
    ["el solar (para construcción)", "building site, terrain à batir"],
    ["la tarjeta de crédito", "credit card"],
    ["la tienda de ultramarinos", "grocer's/grocery (shop)"],
    ["la verja", "railing(s); iron gate"],
    ["la zapatería", "shoe shop"],
    ["la abeja", "bee"],
    ["el águila", "eagle"],
    ["el aire", "air"],
    ["el alud", "avalanche"],
    ["la araña", "spider"],
    ["el árbol", "tree"],
    ["el arbusto", "bush, shrub"],
    ["el arco iris", "rainbow"],
    ["arder", "to burn, to blaze"],
    ["la arena", "sand"],
    ["el arroyo", "le ruisseau"],
    ["la atmósfera", "atmosphere"],
    ["la avispa", "wasp"],
    ["la bahía", "bay"],
    ["el bosque", "wood(s), forest"],
    ["brillar", "to shine"],
    ["la brisa", "breeze"],
    ["el burro", "donkey"],
    ["el caballo", "horse"],
    ["el caracol", "snail"],
    ["la cascada", "waterfall"],
    ["el cerdo", "pig"],
    ["la charca", "pond, étang"],
    ["el clima", "climate"],
    ["el cocodrilo", "crocodile"],
    ["la colina", "hill"],
    ["el conejo", "rabbit"],
    ["la constelación", "constellation"],
    ["el continente", "continent"],
    ["la costa", "coast"],
    ["crecer", "to grow, to increase"],
    ["la cucaracha", "cockroach"],
    ["el desierto", "desert"],
    ["el elefante", "elephant"],
    ["erosionar", "to erode"],
    ["el espacio", "space"],
    ["está lloviendo", "it's raining"],
    ["está nevando", "it's snowing"],
    ["está nublado", "it's cloudy"],
    ["la estrella", "star"],
    ["fértil", "fertile"],
    ["florecer", "to flower, to bloom, to blossom"],
    ["el fuego", "fire"],
    ["la galaxia", "galaxy"],
    ["el granizo", "la grêle"],
    ["hace calor", "it's hot/warm"],
    ["hace sol", "it's sunny"],
    ["hace viento", "it's windy"],
    ["hay niebla", "it's foggy"],
    ["la helada", "givre"],
    ["el hielo", "ice"],
    ["la hierba", "grass; herb"],
    ["la hoja", "leaf"],
    ["la hormiga", "ant"],
    ["húmedo", "humid; damp, wet"],
    ["el huracán", "hurricane"],
    ["el insecto", "insect"],
    ["la inundación", "innondation"],
    ["la jungla", "jungle"],
    ["el lago", "lake"],
    ["el león", "lion"],
    ["la llovizna", "drizzle"],
    ["la lluvia", "rain"],
    ["lluvioso", "pluvieux"],
    ["el lobo", "wolf"],
    ["la lombriz", "(earth)worm"],
    ["el mar", "la mer"],
    ["la marea", "tide"],
    ["la mariposa", "butterfly"],
    ["muerto", "dead"],
    ["el murciélago", "bat"],
    ["la naturaleza", "nature"],
    ["la niebla", "fog, mist"],
    ["la nieve", "snow"],
    ["el nubarrón", "storm cloud"],
    ["la nube", "cloud"],
    ["el océano", "ocean"],
    ["la ola", "wave"],
    ["orbitar", "to orbit"],
    ["la orilla", "shore, (river)bank"],
    ["el oso", "bear"],
    ["la oveja", "sheep"],
    ["el pantano", "le marais, swamp"],
    ["el pez", "fish"],
    ["la piedra", "stone"],
    ["el planeta", "planet"],
    ["la planta", "plant"],
    ["poco profundo", "shallow, not very deep"],
    ["el pollo", "chicken"],
    ["el prado", "meadow, field; pasture"],
    ["profundo", "deep"],
    ["pudrirse", "to rot, to decay"],
    ["la raíz", "root"],
    ["la rama", "branch"],
    ["el ratón", "mouse"],
    ["el relámpago", "(flash of) lightning"],
    ["reproducirse", "se reproduire"],
    ["el río", "river"],
    ["la roca", "rock"],
    ["seco", "dry"],
    ["la semilla", "la semence"],
    ["la serpiente", "le serpent"],
    ["el sistema solar", "solar system"],
    ["el tallo", "stem, la tige"],
    ["el terremoto", "earthquake"],
    ["el tiempo", "weather"],
    ["la tierra", "earth, soil, land"],
    ["el tigre", "tiger"],
    ["la tormenta", "storm"],
    ["el tronco", "(tree) trunk"],
    ["el trueno", "thunder"],
    ["la vaca", "cow"],
    ["el valle", "valley"],
    ["la vegetación", "vegetation"],
    ["la ventisca", "blizzard, tempête de neige"],
    ["el viento", "wind"],
    ["vivo", "living, live, alive"],
    ["el volcán", "volcano"],
    ["el zorro", "fox"],
    ["agudo", "acute; sharp"],
    ["el anticonceptivo", "contraceptive"],
    ["el antiséptico", "antiseptic"],
    ["el asma", "asthma"],
    ["la barbilla", "le menton"],
    ["el bigote", "moustache"],
    ["el brazo", "arm"],
    ["el cabestrillo", "sling"],
    ["la cadera", "hip"],
    ["la cara", "le visage (1)"],
    ["la carne", "flesh"],
    ["la ceja", "eyebrow"],
    ["el cerebro", "brain"],
    ["la cicatriz", "scar"],
    ["la cintura", "waist"],
    ["la cirugía", "surgery"],
    ["el codo", "elbow"],
    ["contagioso", "contagious, infectious"],
    ["el cráneo", "skull"],
    ["el cuello", "neck"],
    ["débil", "weak, feeble, frail"],
    ["el dedo", "finger"],
    ["el dedo (del pie)", "toe"],
    ["el dedo gordo", "big toe"],
    ["dejar de fumar", "to give up smoking, to stop/quit smoking"],
    ["descansar", "se reposer"],
    ["desmayarse", "to faint, to swoon"],
    ["el diente", "tooth"],
    ["doloroso", "painful"],
    ["la dosis", "dose"],
    ["los efectos secundarios", "side effects"],
    ["el diagnóstico", "diagnosis"],
    ["el empaste", "filling"],
    ["enfermar", "to fall/become ill, to be taken ill"],
    ["la enfermedad", "illness, sickness; disease"],
    ["enfermo", "ill"],
    ["la epidemia", "epidemic"],
    ["la erupción (cutánea)", "rash, (skin) eruption"],
    ["la espalda", "le dos"],
    ["el espinazo", "spine, backbone"],
    ["el esqueleto", "skeleton"],
    ["el estómago", "stomach"],
    ["en (buena) forma", "en forme"],
    ["frente", "le front (forehead)"],
    ["el furúnculo", "furoncle"],
    ["la garganta", "throat"],
    ["el grano", "spot, pimple"],
    ["grave", "serious, grave, critical; severe"],
    ["la gripe", "la grippe"],
    ["hacer ejercicio", "to (take) exercise, to do/get some exercise"],
    ["la herida", "wound, injury"],
    ["el hígado", "le foie"],
    ["el hombro", "shoulder"],
    ["el hueso", "bone"],
    ["el infarto", "heart attack"],
    ["la ingle", "groin"],
    ["la inyección", "injection"],
    ["la jeringa", "syringe"],
    ["el labio", "lip"],
    ["la lengua", "tongue"],
    ["la mandíbula", "la machoire"],
    ["la mano", "hand"],
    ["mantenerse en forma", "to keep fit"],
    ["estar mareado", "to feel sick/dizzy"],
    ["el medicamento", "medicine, drug"],
    ["la mejilla", "cheek"],
    ["el miembro", "limb, le membre"],
    ["la muleta", "crutch"],
    ["la muñeca", "poignet"],
    ["el músculo", "muscle"],
    ["el muslo", "la cuisse"],
    ["la nariz", "nose"],
    ["la oreja", "ear"],
    ["el órgano", "organ"],
    ["el/la paciente", "patient"],
    ["pálido", "pale"],
    ["el pecho", "chest, breast"],
    ["el pelo", "hair"],
    ["el pene", "penis"],
    ["la pestaña", "le cil"],
    ["el pie", "foot"],
    ["la piel", "skin"],
    ["la pierna", "leg"],
    ["la píldora", "pill"],
    ["el preservativo", "condom"],
    ["el pulgar", "thumb"],
    ["el pulmón", "lung"],
    ["el pulso", "pulse"],
    ["la receta", "prescription (Médical)"],
    ["recuperarse", "to recover, to get better, to recuperate"],
    ["el resfriado", "cold, le refroidissement"],
    ["resfriarse", "to catch/get a cold"],
    ["el riñón", "kidney"],
    ["la rodilla", "knee"],
    ["romperse la pierna", "to break one's leg"],
    ["ronco", "hoarse"],
    ["la sangre", "blood"],
    ["sano", "en bonne santé, sain"],
    ["el sedante", "sedative"],
    ["la silla de ruedas", "wheelchair"],
    ["el somnífero", "sleeping pill/tablet"],
    ["el sudor", "la sueur"],
    ["sufrir (de)", "to suffer (from)"],
    ["el talón", "heel"],
    ["tener dolor de cabeza", "to have a headache"],
    ["tener dolor de espalda", "to have (a) backache"],
    ["tener dolor de estómago", "to have (a) stomach ache"],
    ["tener dolor de muelas", "to have (a ) toothache"],
    ["la tensión", "blood pressure"],
    ["el termómetro", "thermometer"],
    ["la tirita", "(sticking) plaster, sparadrap"],
    ["el tobillo", "la cheville"],
    ["tomar la píldora", "to be on the pill"],
    ["el tratamiento", "treatment"],
    ["el tumor", "tumour, growth"],
    ["la úlcera", "ulcer"],
    ["la uña", "(finger/toe)nail"],
    ["la vejiga", "la vessie"],
    ["la venda", "bandage"],
    ["el veneno", "poison, venom"],
    ["el vientre", "le ventre, belly"],
    ["butaca", "fauteuil (par ex. théatre)"],
    ["alcanzar a hacer", "arriver à faire"],
    ["matiz", "nuance, teinte"],
    ["abanico", "éventail"],
    ["subrayar", "souligner"],
    ["reja", "grille, barrière "],
    ["cita", "meeting"],
    ["estornudar", "niesen"],
    ["lograr", "réussir"],
    ["alubia", "haricots secs"],
    ["garbanzo", "pois chiches"],
    ["auge", "apogée"],
    ["acuciar", "faire pression, harasser"],
    ["lograr hacer algo", "réussir à faire quelque chose"],
    ["viga", "Balken"],
    ["mendigo", "Bettler"],
    ["difundir", "difuser, répandre"],
    ["pieza", "Stück, Anteil, Teil, Partie"],
    ["revés", "Rückseite, Kehrseite, Hinterseite"],
    ["quebradura", "fissure, hernie"],
    ["complacer", "faire plaisir à"],
    ["mear", "pinkeln"],
    ["cerda, cochina", "Sau"],
    ["contratar", "öffentlich ausschreiben, verdingen, einen Vertrag schließen"],
    ["habitante", "Bewohner, Einwohner, Insasse"],
    ["cinta", "bande, cassette"],
    ["ala", "Fittich, Flügel"],
    ["rana", "Frosch"],
    ["remar", "rudern"],
    ["quebrar", "rompre, casser (un baton, pas une tasse)"],
    ["escasear", "to be scarce"],
    ["abonos", "engrais"],
    ["sordo", "taub"],
    ["colchón", "Matratze"],
    ["conocimientos", "Bekanntschaft"],
    ["oído", "Gehör"],
    ["chaleco", "gilet"],
    ["ciego", "blind"],
    ["temporada", "Jahreszeit, Saison"],
    ["deducir", "ableiten, deduzieren, folgern, schließen"],
    ["contradecir", "widersprechen"],
    ["tamaño", "Dimension, Format, Größe"],
    ["turco", "türkisch, Türke"],
    ["administración", "Verwaltung"],
    ["llano", "plat (superficie)"],
    ["dietario, agenda", "Agenda, Notizbuch"],
    ["red", "Netz"],
    ["arriesgar", "risquer"],
    ["arreglar", "réparer"],
    ["birrete", "chapeau pour juges, cardinaux"],
    ["roncar", "schnarchen"],
    ["engañar", "betrügen, hintergehen, täuschen"],
    ["chanza, burla, broma", "Jux, Scherz, Spaß"],
    ["despedida", "Abschied"],
    ["relevo", "la relève"],
    ["trucha", "Forelle"],
    ["atento", "attentif, attentionné"],
    ["Escocia", "Schottland"],
    ["deseo", "désir, Lust"],
    ["rezar", "beten (Gott)"],
    ["trastornarse", "perdre la tête"],
    ["mosca", "Fliege"],
    ["conservador", "konservativ"],
    ["de memoria", "auswendig, aus dem Kopf"],
    ["aviso", "Warnung, Ankündigung, Benachrichtigung"],
    ["cuota", "Beitrag, cotisation"],
    ["detalle", "Einzelheit, Detail"],
    ["monopolio", "Monopol, Alleinverkauf, Alleinvertrieb"],
    ["apoplejía", "Schlag(anfall), Schlagfluß"],
    ["juntarse", "zusammenkommen, sich vereinigen, zusammengehen"],
    ["igualdad", "Gleichheit"],
    ["campanilla", "Glocke, Klingel"],
    ["baloncesto", "Basketball"],
    ["hondo", "profond"],
    ["espeso", "épais"],
    ["agudo", "tranchant, aigu"],
    ["borracho", "bouré, betrunken"],
    ["alambre", "Draht, fil de fer"],
    ["alcanzar", "atteindre, ratrapper"],
    ["gemelos", "Zwillinge, Zwilling"],
    ["saldar", "solder"],
    ["acumulador", "Batterie"],
    ["asir", "saisir"],
    ["hornada", "Backwerk, Gebäck"],
    ["basurero", "éboueur"],
    ["engaño", "Betrug, Täuschung"],
    ["diputado", "Abgeordneter, Delegierter"],
    ["escopeta", "Gewehr"],
    ["deplorable", "bedauerlich, bedauernswert, erbärmlich"],
    ["quemadura", "Verbrennung, Brandwunde"],
    ["gobierno", "Regierung"],
    ["acometer", "entreprendre, s'attaquer à"],
    ["esparadrapo", "Pflaster"],
    ["tronar", "donnern"],
    ["pino", "Kiefer"],
    ["bizcocho", "Keks, Plätzchen, Zwieback"],
    ["minoría", "Minderheit"],
    ["impuesto", "Abgabe, Steuer, Steuerabgabe"],
    ["anchura", "Breite"],
    ["trazar", "tracer, évoquer"],
    ["bandera", "Fahne, Flagge"],
    ["provecho", "le profit"],
    ["encarecer", "stark empfehlen, anpreisen"],
    ["jarra", "Kanne, Krug"],
    ["párrafo", "paragraphe"],
    ["puntiagudo", "spitz"],
    ["granja, finca", "Bauernhof, Besitzung, Gut, Landgut"],
    ["desarrollar", "développer, mettre au point"],
    ["parir", "to give birth"],
    ["hortaliza", "légume (dans le potager, pas dans assiette)"],
    ["resabio", "arriêre-gout (americain)"],
    ["estancarse", "stagner"],
    ["paloma", "pigeon"],
    ["flaco", "mince (une personne), faible (un argument)"],
    ["vaciar", "vider"],
    ["arraigar", "prendre racine"],
    ["tibio", "tiède"],
    ["cuchichear", "flüstern"],
    ["ausente", "abwesend"],
    ["heredar", "erben, beerben"],
    ["el anochecer", "le crépuscule, Dämmerung"],
    ["prejuicio", "Vorurteil"],
    ["queja", "Beschwerde, Klage"],
    ["acreedor", "Gläubiger"],
    ["entusiasmar", "begeistern"],
    ["baranda", "rampe, balustrade"],
    ["comarca", "Region (dans sens spécialisé)"],
    ["alcanzable", "réalisable"],
    ["sustraer", "abziehen, subtrahieren"],
    ["compañía", "Gesellschaft, firme"],
    ["campamento", "Campingplatz, Zeltplatz, Lager, Zeltlager"],
    ["mayoría", "Mehrheit"],
    ["silbar", "pfeifen"],
    ["acomodado", "wohlhabend"],
    ["apoyarse", "sich stützen"],
    ["vengar", "rächen"],
    ["verter", "verser, einschenken"],
    ["cañón", "Kanon, Kanone"],
    ["asentir", "bejahen, ja sagen"],
    ["mirada", "Blick"],
    ["tapa", "couvercle"],
    ["abeto", "Fichte, Tanne"],
    ["fregar", "aufwaschen"],
    ["a propósito", "absichtlich"],
    ["farsante", "imposteur, comédien"],
    ["porciento", "Prozent, Zins"],
    ["aplauso", "Applaus, Beifall"],
    ["negocio", "Unternehmung, affaire"],
    ["bombón", "Bonbon"],
    ["vergüenza", "Scham, Schande"],
    ["caucho", "Gummi"],
    ["pasillo", "Gang, Hausflur, Flur, Korridor"],
    ["sacerdote", "Priester"],
    ["autovía", "Autobahn, Schnellstraße"],
    ["robo", "Diebstahl"],
    ["acometida", "Anfall, Angriff, Offensive"],
    ["cortadura", "Einschnitt, Schnitt"],
    ["atornillar", "schrauben"],
    ["aliento", "Atem, haleine"],
    ["tetera", "Teekanne, Teebüchse"],
    ["tijeras", "ciseaux"],
    ["quejarse", "klagen, sich beklagen, verklagen"],
    ["pavo", "Truthahn"],
    ["rueda posterior", "Hinterrad"],
    ["sendero", "Fußweg, Pfad, Steg, Steig"],
    ["maquinar", "comploter"],
    ["abrogar", "abroger"],
    ["sospechar", "verdächtigen, suspecter"],
    ["voltaje", "Spannung, tension électrique"],
    ["llama", "Flamme"],
    ["anualmente", "jährlich"],
    ["adjetivo", "Adjektiv, Eigenschaftswort"],
    ["tomo", "Band, Volumen"],
    ["convenio", "Akkord, Abkommen"],
    ["deletrear", "buchstabieren"],
    ["helicóptero", "Hubschrauber"],
    ["diariamente", "täglich, alltäglich"],
    ["medroso", "craintif "],
    ["el corriente", "Strom, strömend, Strömung, elektrischer Strom"],
    ["almendra", "Mandel"],
    ["cazar", "jagen"],
    ["afeitar", "barbieren, rasieren"],
    ["tutear", "duzen"],
    ["a cuadros", "kariert"],
    ["viña", "Weinberg"],
    ["ahogarse", "ersaufen, ertrinken"],
    ["riesgo", "Risiko, Wagnis"],
    ["pichón", "Taube jung"],
    ["baya", "Beere"],
    ["temer", "befürchten, sich ängstigen, zagen"],
    ["amenaza", "Menace"],
    ["mantel", "Tischtuch"],
    ["derribar", "niederreißen, abbauen"],
    ["crimen", "le crime"],
    ["octavo", "achte"],
    ["puño", "Faust"],
    ["apresurarse", "eilen, sputen"],
    ["gratuito", "unentgeltlich"],
    ["enmohecerse", "schimmeln, verschimmeln"],
    ["ladrón", "Dieb"],
    ["el premio", "le prix, award"],
    ["mojado", "nass"],
    ["sótano", "Keller"],
    ["barrio", "Stadtviertel, Viertel"],
    ["afán", "ardeur"],
    ["huir", "fliehen, flüchten"],
    ["ausencia", "Abwesenheit"],
    ["tributo", "Abgabe, Steuer, Steuerabgabe, Tribut"],
    ["arrancar", "arracher, enlever (aussi: faire démarrer auto)"],
    ["taco", "Nagel, Stift"],
    ["estufa", "Herd, cuisinière"],
    ["medir", "messen, abmessen"],
    ["mármol", "Marmor"],
    ["IVA", "Mehrwertsteuer"],
    ["afectuosidad", "Anhänglichkeit, Hingabe"],
    ["sello", "Briefmarke, Gepräge, Stempel"],
    ["cámara de aire", "Schlauch (vélo)"],
    ["parte trasera", "Hinterseite, Rückseite"],
    ["huelga", "streik, grève"],
    ["avergonzarse", "sich schämen"],
    ["solterón, soltero", "Junggeselle"],
    ["conminar", "sommer, enjoindre"],
    ["goma", "Gummi, Radiergummi"],
    ["Suiza", "Schweiz, die Schweiz"],
    ["departamento", "département "],
    ["atreverse", "oser, sich wagen"],
    ["conducirse", "sich aufführen, sich benehmen, sich betragen, sich verhalten"],
    ["computador, ordenador", "Computer, Datenverarbeiter, Zähler, Rechner"],
    ["reñir", "gronder, se disputer"],
    ["sastre", "Schneider"],
    ["vena", "Ader, Vene"],
    ["fidedigno", "authentique, fiable"],
    ["en el extranjero", "im Ausland"],
    ["con agrado", "avec satisfaction"],
    ["despedirse", "verabschieden, ausloggen"],
    ["ganancia", "Errungenschaft (monétaire)"],
    ["quedar", "rester"],
    ["accionista", "Aktieninhaber, Aktionär"],
    ["cartera", "Aktentasche"],
    ["tocar la campanilla", "anläuten, klingeln, anklingeln"],
    ["bandeja", "Präsentierteller, Tablett"],
    ["tinta", "Tinte"],
    ["vatio", "Watt"],
    ["vela", "Kerze, Licht"],
    ["taller", "Atelier, Werkstatt"],
    ["insolación", "Sonnenbrand, Sonnenstich"],
    ["instigar", "inciter qq à faire qq chose"],
    ["coronar", "krönen"],
    ["sosegado", "paisible, discret"],
    ["resumen", "Übersicht, résumé"],
    ["sembrar", "säen"],
    ["registrar", "enregistrer, perquisitioner"],
    ["estación de servicio", "Tankstelle"],
    ["compromiso", "Kompromiss"],
    ["boda", "Hochzeit"],
    ["de hierro", "eisern, aus Eisen"],
    ["astilla", "Splitter"],
    ["mono", "Affe"],
    ["celebrar su cumpleaños", "Geburtstag haben"],
    ["derruir", "démolir"],
    ["desmoronarse", "tomber (par soi même): personne (médical) ou batiment"],
    ["asegurador", "Versicherer"],
    ["domicilio", "Wohnort, Wohnsitz"],
    ["eslavo", "slawisch, Slawe"],
    ["dar a destajo", "öffentlich ausschreiben"],
    ["Cristo", "Christus"],
    ["asombrarse", "sich wundern, staunen, s'émerveiller"],
    ["descuidar", "vernachlässigen"],
    ["pretensión", "Heiratsantrag, Anspruch"],
    ["empujar", "pousser, bousculer"],
    ["bucear", "tauchen, eintauchen, untertauchen"],
    ["escarpado", "abschüssig, steil"],
    ["cueva", "Grotte, Grube, Höhle"],
    ["dimitir", "zurücktreten, sein Amt niederlegen, demissionieren, abdanken"],
    ["pleamar", "Pleine mer"],
    ["tirante", "tendu (relation ou objet)"],
    ["pico", "Schnabel, Specht"],
    ["chuleta", "Kotelett, Schnitzel"],
    ["oca", "Gans"],
    ["entregar", "livrer, remettre"],
    ["rebanada", "tranche (de pain), morceau"],
    ["franqueo", "Frankatur, Porto"],
    ["obispo", "Bischof"],
    ["cuesta", "pente, côte"],
    ["digresar", "vom Thema abkommen"],
    ["adelantar", "überholen"],
    ["Alcorán", "Koran"],
    ["conocimiento", "Begriff, Kenntnis, Kenntnisse"],
    ["remitente", "Absender"],
    ["rebaja", "Nachlass, Rabatt"],
    ["estanco", "Tabakladen"],
    ["aconsejar", "raten, beraten, ratgeben"],
    ["estipular", "stipuler"],
    ["vidrio", "Glas (vitre)"],
    ["semejante", "ähnlich"],
    ["agujero", "Loch"],
    ["tranvía", "Straßenbahn"],
    ["lápiz", "Bleistift"],
    ["ternero", "Kalb"],
    ["reír", "lachen"],
    ["redondo", "rund"],
    ["en vano", "umsonst, vergebens, vergeblich"],
    ["alquilar", "mieten; vermieten"],
    ["quemar", "verbrennen"],
    ["lazo", "un noeud, un lien (entre personnes)"],
    ["ampolla", "Birne, Glühbirne; Blase"],
    ["aldea", "Dorf, Ort"],
    ["sombra", "Schatten"],
    ["morar", "wohnen, demeurer"],
    ["gritar", "schreien"],
    ["peine", "Kamm"],
    ["alcalde", "Bürgermeister"],
    ["acero", "Stahl"],
    ["abridor de tapones", "Flaschenöffner"],
    ["cenicero", "Aschenbecher"],
    ["acariciar", "schmeicheln, carresser"],
    ["trepar", "klettern, klimmen"],
    ["tornillo", "Schraube"],
    ["cojo", "hinkend, lahm"],
    ["friolero", "frileux"],
    ["trineo", "traineau, luge"],
    ["pezuña", "sabot (de cheval)"],
    ["diestro", "fix, geschickt, geübt, gewandt"],
    ["prisión", "Gefängnis, Verlies"],
    ["hojalata", "Blech"],
    ["morder", "beißen"],
    ["ajuar", "Mobilier, trousseau de mariage"],
    ["estuche", "étui, trousse"],
    ["sudar", "schwitzen"],
    ["ejército", "Armee, Heer"],
    ["cesión", "Verzicht, Ausstieg, Abtretung"],
    ["extraviarse", "sich verirren"],
    ["bujía", "(Zünd-)Kerze"],
    ["celo", "zèle"],
    ["código", "Code"],
    ["fideos", "Nudel, nouilles"],
    ["fiel", "gläubig, treu"],
    ["cohete", "Rakete"],
    ["regar", "arroser"],
    ["camarote", "une cabine"],
    ["martillo", "Hammer"],
    ["llanura", "Ebene"],
    ["silvestre", "sauvage (plantes)"],
    ["arrebatar", "to grab, to snatch, attraper"],
    ["calabaza", "potiron"],
    ["rescate", "sauvetage, rancon"],
    ["imprenta", "imprimerie, druckerei"],
    ["cohecho", "forme de corruption"],
    ["paro", "chômage"],
    ["parado", "chômeur"],
    ["fomentar", "promouvoir"],
    ["el fuero", "privilège (d'un politicien, etc)"],
    ["fracasar", "échouer"],
    ["forastero", "étranger (à une ville, une région)"],
    ["extranjero", "étranger (à un pays)"],
    ["fallecer", "décéder"],
    ["fallar", "échouer, rater, céder (des freins, par ex.)"],
    ["hace una hora", "il y a une heure"],
    ["volver a dormir", "go back to sleep"],
    ["dejar de dormir", "stop sleeping"],
    ["acabo de ir al cine", "I have just been to the cinema"],
    ["tengo ganas de ir al parque", "I feel like going to the park"],
    ["tengo que limpiar mi dormitorio", "I have to clean my bedroom (force 1)"],
    ["mi estomago me hace daño", "j'ai mal à l'estomac"],
    ["es mi culpa", "c'est de ma faute"],
    ["por lo visto", "apparently"],
    ["por eso", "therefore"],
    ["por ejemplo", "par exemple"],
    ["es lo tuyo", "it is yours"],
    ["lo importante es que", "the important things is that"],
    ["ni yo tampoco", "me neither"],
    ["debo hacerlo", "I must do it (force 2)"],
    ["tengo prisa", "I am in a hurry"],
    ["tengo sueño", "I am sleepy"],
    ["¿Quién(es)?", "who?"],
    ["¿Cuál(es)?", "which?"],
    ["antes de", "avant de"],
    ["después de", "après que"],
    ["hace poco tiempo", "il n'y a pas longtemps"],
    ["dentro de poco", "bientôt"],
    ["sicario", "tueur à gages"],
    ["el perito", "l'expert"],
    ["fiscalizar", "superviser, réguler"],
    ["rueda de prensa", "conférence de presse"],
    ["el campesino", "le paysan"],
    ["acotar", "délimiter"],
    ["todavìa non han llegado", "ils ne sont pas encore arrivés"],
    ["ya no como", "je ne mange plus"],
    ["desde 1985", "depuis 1985"],
    ["desde hace dos meses", "depuis deux mois"],
    ["estoy a punto de empezar", "je suis sur le point de commencer"],
    ["aplastar", "aplatir"],
    ["clavar", "clouer"],
    ["celoso", "jaloux"],
    ["tragar", "avaler"],
    ["pardo", "qui est de couleur brune (ours par ex.)"],
    ["sacudir", "secouer (physiquement, émotionnellement)"],
    ["asustado", "effrayé, scared"],
    ["tropezar", "trébucher"],
    ["liso", "lisse"],
    ["derrotar", "imposer une défaite, to defeat"],
    ["herir", "blesser"],
    ["mudo", "muet"],
    ["valiente", "brave, courageux"],
    ["apostar", "parier"],
    ["traicionar", "trahir"],
    ["callado", "calme, réservé"],
    ["atragantarse", "s'étouffer, s'étrangler"],
    ["trozo", "un morceau (de pain, par ex.)"],
    ["trasvasar", "transférer"],
    ["el declive", "le déclin"],
    ["gastar", "dépenser (de l'énergie), consommer, user (les chaussures)"],
    ["largarse", "ficher le camp"],
    ["sambenito", "la mauvaise réputation, le discrédit"],
    ["pegamento", "la colle"],
    ["chaval", "gosse, gamin"],
    ["vecindario", "voisinage"],
    ["agachar", "baisser (la tête,…)"],
    ["jaleo", "pagaille"],
    ["roce", "frottement, heurt (aussi entre populations)"],
    ["degollar", "égorger, massacrer"],
    ["parroquiano", "paroissien"],
    ["milagro", "miracle"],
    ["humilde", "humble"],
    ["pedazo (de madera)", "morceau (de bois)"],
    ["deslavazado", "incohérent (un discours), sans consistence (structure)"],
    ["menudeo", "vente au détail (de drogue..)"],
    ["entorno", "environnement, milieu"],
    ["letrado", "avocat"],
    ["tesorero", "trésorier"],
    ["tildar de", "traiter de (traiter de terroriste, par ex.)"],
    ["desafío", "le défi"],
    ["capa (capa social)", "la couche (la couche sociale)"],
    ["huérfano", "orphelin"],
    ["granero", "grenier"],
    ["buzo", "homme grenouille, plongeur"],
    ["rastrear", "retracer, retrouver (une boite noire, apr ex.)"],
    ["despegar", "décoller (un avion)"],
    ["pesquisa", "enquête, recherches"],
    ["homenaje", "hommage"],
    ["destacar", "souligner, mettre en valeur"],
    ["tirotear", "tirer sur (avec arme)"],
    ["recalcar", "souligner, insister"],
    ["altillo", "grenier (2)"],
    ["buhardilla (altillo abuhardillado)", "mansarde"],
    ["abuhardillado", "mansardé"],
    ["encabezar", "prendre la tête, mener, présider"],
    ["fianza", "la caution"],
    ["desamparo", "détresse"],
    ["derrocar", "renverser (un régime par ex.)"],
    ["agregar", "ajouter à (aussi dans un discours)"],
    ["beca", "bourse (d'études aussi)"],
    ["entregarse a", "se consacrer à"],
    ["alicaído", "abattu (mentalement)"],
    ["rótulo", "un panneau, une enseigne"],
    ["padecer de", "souffrir de"],
    ["chorro", "le jet (d'eau)"],
    ["fecha y plazo", "la date et l'heure"],
    ["desplome", "collapse, effondrement (économique)"],
    ["la tasa", "le taux (par ex. Chômage)"],
    ["rozar", "frôler (des chiffres, mais aussi physiquement)"],
    ["estafa", "escroquerie"],
    ["rescatar", "secourir, libérer"],
    ["rastro", "trace"],
    ["leve", "léger"],
    ["herramienta", "outil"],
    ["escayola", "platre (matière)"],
    ["serrar", "scier"],
    ["atar", "nouer, attacher"],
    ["destornillador", "tournevis"],
    ["tenaza", "beisszange, pince"],
    ["tuerca", "écrou, Mutter"],
    ["rehén", "otage"],
    ["colillas", "mégots de cigarette"],
    ["la junta", "la réunion, le comité"],
    ["hundimiento", "naufrage"],
    ["hundir", "couler (un bateau), s'enfoncer"],
    ["escaño", "le siège (au parlement)"],
    ["rumbo", "le cap, la direction"],
    ["espuma", "la mousse"],
    ["bisagra", "charnière"],
    ["escolta", "escorte"],
    ["otorgar", "octroyer, accorder"],
    ["holgado", "ample"],
    ["hilera", "une rangée (des maisons par ex.)"],
    ["indagar", "enquêter, rechercher"],
    ["trasiego", "mouvement, passage, transfert "],
    ["caudillo", "seigneur de guère"],
    ["aseverar", "assurer, affirmer"],
    ["salpicar", "éclabousser, gicler"],
    ["desgarrar", "déchiqueter, arracher, déchirer"],
    ["arruga", "une ride, un pli"],
    ["azafata", "hôtesse de l'air"],
    ["enlace", "une liaison, une correpondance (train...)"],
    ["estofado", "ragôut"],
    ["paja", "la paille"],
    ["los callos", "les tripes"],
    ["la yema", "le jaune d'oeuf"],
    ["el blanquillo", "blanc d'oeuf"],
    ["acontecer", "se passer, arriver"],
    ["agarrar", "saisir"],
    ["charlar", "bavarder"],
    ["plegar", "plier"],
    ["estallar", "exploser"],
    ["mimbre", "osier"],
    ["soborno", "corruption"],
    ["multa", "amende, contravension"],
    ["tiro", "le coup de feu"],
    ["propina", "pourboire"],
    ["soga", "corde"],
    ["navaja", "canif"],
    ["huerto", "verger"],
    ["hueso", "noyau"],
    ["avellana", "noisette"],
    ["sollozo", "sanglot"],
    ["seguidismo", "blindes nacheifern"],
    ["víspera", "la veille (le jour avant)"],
    ["merecer", "mériter"],
    ["imprescindible", "indispensable"],
    ["nítido", "net, clair"],
    ["rodeo", "détour"],
    ["enmienda", "amendement, amélioration"],
    ["apostar por", "miser sur"],
    ["guiño", "clin d'oeil"],
    ["estrujar", "presser, serrer"],
    ["presupuesto", "budget"],
    ["aplazar", "ajourner"],
    ["ataúd", "cercueil"],
    ["vincular", "établir un lien (entre des sujets, des personnes)"],
    ["en vilo", "en suspens, en haleine"],
    ["reto", "défi, menace"],
    ["gozar de", "jouir de"],
    ["predicamento", "prestige"],
    ["por despecho", "par dépit"],
    ["pantalla", "écran"],
    ["bruja", "sorcière"],
    ["hoguera", "bûcher"],
    ["paulatinamente", "progressivement"],
    ["hito", "tournant, étape, fait historique"],
    ["brotar", "jaillir, pousser (plante)"],
    ["encauzar", "orienter, canaliser"],
    ["novatada", "bizutage"],
    ["verdugo", "bourreau"],
    ["estampa", "l'image, l'allure"],
    ["rechazar", "rejetter (une idée), repousser"],
    ["suministrar", "fournir (des armes, ...)"],
    ["afianzar(se)", "consolider (s'établir)"],
    ["agotar (se)", "épuiser (s'épuiser)"],
    ["acosar", "harceler, stalk, tyraniser"],
    ["jactancioso", "vantard"],
    ["trazo", "trait"],
    ["suavizar", "adoucir"],
    ["canje", "échange (de prisonniers)"],
    ["estrenar", "inaugurer"],
    ["cumbre", "sommet (politique)"],
    ["limar asperezas", "passer l'éponge"],
    ["torpe", "maladroit"],
    ["acorralar", "acculer, forcer dans les retranchements"],
    ["trama", "machination, intrigue"],
    ["eventual", "temporaire (travail)"],
    ["ubicado", "situé"],
    ["anhelo", "aspiration, désir"],
    ["anhelar hacer", "mourir d'envie de faire, aspirer à faire"],
    ["disparo", "coup de feu (2)"],
    ["apodar", "surnommer"],
    ["poderoso", "puissant"],
    ["azotar", "fouetter"],
    ["escabullirse", "filer, s'esquiver"],
    ["recaudar", "percevoir (des impôts)"],
    ["cosechar", "récolter"],
    ["entorpecer", "gêner, entraver"],
    ["abastecer (se)", "approvisionner  (s'approvisionner)"],
    ["ahorro", "épargne, économie"],
    ["arrimar", "approcher"],
    ["cúspide", "point culminant"],
    ["hallazgo", "découverte"],
    ["lancha", "canot"],
    ["atajo", "raccourci"],
    ["atajar", "couper court, interrompre"],
    ["segar", "tondre (l'herbe), interrompre de manière violente et brusque (la vie)"],
    ["telón", "rideau"],
    ["vaticinio", "prédiction"],
    ["cauto", "prudent"],
    ["tentempié", "casse-croute, snack"],
    ["arrodillarse", "s'agenouiller"],
    ["arrollar", "renverser, écraser (avec une voiture, ou fig.)"],
    ["mimado", "gâté (un enfant)"],
    ["pisotear", "piétiner, fouler aux pieds, bafouer"],
    ["poner de relieve", "mettre en relief"],
    ["reseña", "compte rendu"],
    ["rasgo", "trait (caractéristiques)"],
    ["anzuelo", "hameçon"],
    ["ultrajar", "outrager, indigner"],
    ["bostezo", "baillement"],
    ["turbar", "troubler, gêner"],
    ["cuna", "berceau"],
    ["arropar", "couvrir (avec vêtement, couverture), border "],
    ["mismísimo", "en personne"],
    ["puntero", "de pointe"],
    ["ileso", "indemne"],
    ["varón", "un homme (2)"],
    ["burbuja", "bulle"],
    ["enchufe", "piston (pour un poste....)"],
    ["chanchullo", "magouille"],
    ["pyme", "PME"],
    ["sensatez", "bon sens"],
    ["trampa", "piège"],
    ["aislar", "isoler"],
    ["crujir", "croquer"],
    ["rebaño", "troupeau"],
    ["dar algo prestado", "prêter quelque chose"],
    ["tomar prestado", "emprunter"],
    ["acatar", "respecter, se conformer à"],
    ["redada", "descente (policière)"],
    ["derramar", "verser (du sang, des larmes)"],
    ["cobijo", "abri (héberger: dar...)"],
    ["mueca", "grimace"],
    ["retocar (retoque)", "retoucher (retouche)"],
    ["trámite", "formalité, démarche"],
    ["abogar por", "plaider pour"],
    ["caballa", "maquereau"],
    ["meta", "but, objectif"],
    ["días hábiles", "jours ouvrables"],
    ["sabiduría", "sagesse"],
    ["atascar", "boucher, coincer"],
    ["temblar", "trembler"],
    ["umbral", "seuil (de la pauvreté, par ex.)"],
    ["acudir a", "avoir recours à "],
    ["fraguar", "forger, établir"],
    ["albañil", "maçon"],
    ["fontanero", "plombier"],
    ["cangrejo", "crabe"],
    ["acantilado", "falaise"],
    ["concha", "coquillage"],
    ["guijarro", "caillou, gallet"],
    ["boya", "bouée"],
    ["pala", "pelle"],
    ["oruga", "chenille"],
    ["pulga", "puce"],
    ["tiburón", "requin"],
    ["pantorrilla", "mollet"],
    ["arancel", "droit de douane"],
    ["subastas", "vente aux enchères"],
    ["granel", "en vrac"],
    ["empinado", "en pente, escarpé"],
    ["acechar", "guetter"],
    ["eslabón", "maillon"],
    ["envasar", "conditionner, emballer"],
    ["tesón", "acharnement, tenacité"],
    ["pizarra", "tableau (noir)"],
    ["asignatura", "matière (école), le sujet"],
    ["recurso", "ressource"],
    ["comprobar", "vérifier, constater"],
    ["teclado", "clavier"],
    ["volcarse", "se renverser, chavirer"],
    ["polea", "poulie"],
    ["ladrar", "aboyer"],
    ["palomitas", "pop corn"],
    ["tirar", "jeter"],
    ["caspa", "pellicule (cheveux)"],
    ["horroroso", "horrible"],
    ["un montón de", "un tas de"],
    ["pesadilla", "cauchemar"],
    ["zarza", "ronce, buisson"],
    ["enzarzarse", "se lancer dans un conflit"],
    ["liviano", "léger, trivial"],
    ["voladura", "explosion, dynamitage"],
    ["mitin (mitines)", "meeting (s)"],
    ["títere", "marionnette"],
    ["eje", "axe, ligne centrale"],
    ["ahuyentar", "chasser, mettre en fuite"],
    ["urdir", "comploter, manigancer"],
    ["amparo", "protection"],
    ["lacra", "fléau"],
    ["aventar", "jeter, disperser, exposer au vent"],
    ["aluvión", "torrent (de...), inondation"],
    ["atrevido", "audacieux, osé"],
    ["altivo", "hautain, snob"],
    ["anclaje", "ancrage, fixation"],
    ["copar", "remporter (des postes, lors d'une élection)"],
    ["endeble", "faible, fragile (personne, argument)"],
    ["embudo", "entonnoir"],
    ["estrago", "ravage"],
    ["poner en tela de juicio", "mettre en doute"],
    ["vacuna", "vaccin"],
    ["percatarse", "se rendre compte de "],
    ["horca", "potence"],
    ["horquilla", "fourche, fourchette (de chiffres)"],
    ["sesgo", "biais"],
    ["pega", "obstacle, problème, travail (familier)"],
    ["muestra", "échantillon"],
    ["caudal", "débit (eau, monétaire)"],
    ["medición", "la mesure"],
    ["cauce", "le lit (du fleuve)"],
    ["cabida", "capacité"],
    ["vendaval", "vent violent, tempête"],
    ["zarpazo", "coup de griffe"],
    ["a la chita callando", "en douce, sans tambour ni trompette"],
    ["meollo", "moelle, substance"],
    ["erizo", "hérisson"],
    ["añorar", "avoir la nostalgie de, regretter"],
    ["anonadado", "devastated"],
    ["choza", "hutte"],
    ["lindar con", "être attenant à, border, jouxter"],
    ["lindero", "limitrophe"],
    ["rellano", "le palier"],
    ["emparejar", "mettre ensemble, faire correspondre, assortir"],
    ["tonelada", "une tonne"],
    ["vertedero", "dépotoir, décharge"],
    ["leña", "le bois, le bois de chauffage"],
    ["leñador", "bucheron"],
    ["harapiento", "en haillons"],
    ["harapos", "haillons"],
    ["fingir", "prétendre, simuler, feindre"],
    ["maullido", "miaulement"],
    ["almíbar", "sirop"],
    ["mozo", "jeune homme"],
    ["reanudar", "reprendre, renouer"],
    ["rostro", "visage"],
    ["mofletudo", "jouflu"],
    ["brinco", "un bond"],
    ["achaparrado", "trapu, courtaud"],
    ["mantón", "châle"],
    ["inmutarse", "se troubler"],
    ["rabo", "queue"],
    ["lamer", "lécher"],
    ["leño", "une buche de bois"],
    ["cerilla", "allumette"],
    ["barriga", "ventre, panse"],
    ["talonario", "carnet (de cheques)"],
    ["diezmar", "décimer (gibier par ex)"],
    ["jabalí (jabalíes)", "sanglier"],
    ["ardilla", "écureuil"],
    ["trago", "gorgée"],
    ["enfurruñarse", "se fâcher"],
    ["guisar", "cuisiner, faire cuire"],
    ["embutido", "charcuterie"],
    ["rematar", "achever, parfaire (un travail), mettre aux enchères"],
    ["rodar", "rouler, tourner (un film aussi)"],
    ["rezongar", "ronchonner"],
    ["trabar (amistad, conocimiento, ...)", "lier (connaissance, amitié, ...)"],
    ["mugre", "crasse"],
    ["ceñido", "moulant, serré"],
    ["bata", "robe de chambre, peignoir"],
    ["torbellino", "tourbillon"],
    ["codearse", "côtoyer"],
    ["disfrazar", "déguiser"],
    ["destrozar", "casser, briser"],
    ["ametralladora", "mitrailleuse"],
    ["agobiar", "accabler"],
    ["ocioso", "oisif"],
    ["beato", "pieux, bigot"],
    ["tajante", "catégorique, tranchant"],
    ["atropellar", "écraser, renverser"],
    ["juerga", "orgie, fête"],
    ["hartarse de", "se lasser de, saturer"],
    ["adiestrar", "entraîner"],
    ["grieta", "fissure, brêche"],
    ["regordete", "rondelet, dodu"],
    ["enaguas", "jupon"],
    ["me saca de quicio", "ça me rend fou"],
    ["quicio", "gond"],
    ["regazo", "genoux"],
    ["desván", "grenier (3)"],
    ["baúl", "malle"],
    ["tacaño", "radin"],
    ["calambre", "crampe"],
    ["preñar", "engrosser, rendre enceinte"],
    ["melena", "chevelure, tignasse"],
    ["andurriales", "coin perdu"],
    ["chapuza", "bricole, travail baclé"],
    ["pitar", "claxonner, siffler"],
    ["halagar", "flatter"],
    ["de aúpa", "carabiné"],
    ["hacer tilín a alguien", "plaire à quelqu'un"],
    ["lozano", "vigoureux"],
    ["álamo", "peuplier"],
    ["pormenor", "détail"],
    ["estaño", "étain"],
    ["ajeno", "d'autrui, étranger à"],
    ["paladar", "palais (bucal)"],
    ["cobre", "cuivre"],
    ["parranda", "la bringue, fête, cuite"],
    ["alboroto", "tapage, vacarme"],
    ["gaveta", "tiroir (2)"],
    ["yeso", "plâtre"],
    ["estruendo", "vacarme, grand bruit"],
    ["percance", "contretemps, mésaventure"],
    ["tienta", "sonde"],
    ["a tientas", "à tâtons"],
    ["vejez", "vieillesse"],
    ["sien", "tempe"],
    ["párpado", "paupière"],
    ["rizado", "frisé"],
    ["ave", "oiseau"],
    ["halcón", "faucon"],
    ["lumbre", "feu (de bois)"],
    ["sigilo", "silence"],
    ["sorbo", "gorgée (2)"],
    ["zanjar", "trancher (la question), régler, résoudre"],
    ["alabar", "louer, faire l'éloge de"],
    ["mustio", "flétri (plante), triste (personne)"],
    ["espanto", "frayeur, panique"],
    ["humeante", "fumant"],
    ["inermes", "sans défense, sans armes"],
    ["amargar", "rendre amer, gâcher"],
    ["cebar", "gaver"],
    ["tablón", "planche"],
    ["basto", "rustre, grossier (matière et personne)"],
    ["fachada", "façade"],
    ["alza", "hausse"],
    ["muelle", "quai, dock"],
    ["pétreo", "de la pierre"],
    ["jaula", "cage"],
    ["maceta", "pot de fleur"],
    ["helecho", "fougère"],
    ["amanecer", "lever du jour"],
    ["baldosa", "carreau, dalle"],
    ["desperdicio", "gaspillage, déchets, détrituts"],
    ["apremio", "urgence, contrainte"],
    ["alba", "aube"],
    ["asiento", "siège"],
    ["índole", "nature, genre, caractère, type"],
    ["séquito", "entourage, cour, partisans"],
    ["silbato", "sifflet"],
    ["asombro", "étonnement, stupéfaction"],
    ["pésame", "condoléance"],
    ["desvarío", "délire, divagation"],
    ["alforja", "sacoche"],
    ["becerro", "veau"],
    ["hebilla", "la boucle (d'une ceinture)"],
    ["argolla", "anneau, alliance"],
    ["angosto", "étroit, reserré"],
    ["embadurnar", "badigeonner, beschmieren"],
    ["pleito", "procès, litige"],
    ["desafiar", "affrontrer, mettre au défi"],
    ["rezagado", "en retard"],
    ["comulgar", "communier"],
    ["estremiciento", "frisson"],
    ["travesura", "espièglerie, farce"],
    ["recóndito", "retiré"],
    ["mecedor", "schaukelstuhl  "],
    ["vervena", "kermesse, fête de quartier"],
    ["rifar", "tirer au sort"],
    ["altanero", "hautain"],
    ["ínfulas", "grands airs"],
    ["polaco", "polonais"],
    ["revuelo", "trouble, émoi, sensation"],
    ["turbio", "trouble "],
    ["manso", "doux, docile, apprivoisé"],
    ["monja", "nonne"],
    ["luto", "deuil"],
    ["alborozo", "réjouissance"],
    ["engendro", "monstre"],
    ["medrar", "réussir, prospérer"],
    ["bocina", "klaxon"],
    ["sosegar", "apaiser"],
    ["hechizo", "sorcelerie"],
    ["achacar", "mettre sur le compte de, reprocher"],
    ["calabozo", "taule, cachot"],
    ["indulto", "grâce (juridique)"],
    ["descalabro", "revers, échec"],
    ["tertulia", "talk show, table ronde"],
    ["escollo", "obstacle, pierre d'achoppement"],
    ["topar con", "tomber sur"],
    ["recelar de", "se méfier de"],
    ["descarrilar", "dérailler"],
    ["sosiego", "tranquilité"],
    ["noviazgo", "fiancailles"],
    ["vigilar", "surveiller"],
    ["ciénaga", "marécage, bourbier"],
    ["al alcance de la mano", "à portée de main"],
    ["alcance", "la portée"],
    ["flaqueza", "faiblesse"],
    ["gavilla", "gerbe (fleurs, etc), bande (de voyous)"],
    ["aturdir", "abassourdir"],
    ["bendecir", "bénir"],
    ["ladrillo", "brique"],
    ["empollar", "couver (oiseaux), potasser (étudier, bosser)"],
    ["golondrina", "hirondelle"],
    ["soltar", "lacher (animaux), libérer (otages, prisonniers)"],
    ["res", "bête, boeuf"],
    ["emperrarse", "s'obstiner"],
    ["enderezar", "redresser"],
    ["repentino", "subit, soudain"],
    ["chistera", "chapeau, haut de forme"],
    ["vislumbrar", "entrevoir"],
    ["pandilla", "groupe, clique"],
    ["estorbar", "gêner, entraver, perturber"],
    ["reguero", "une trainée (de poudre, de sang, de poussière)"],
    ["rescoldo", "braise, cendre chaude"],
    ["desperdigar", "disperser, éparpiller"],
    ["ternura", "tendresse, douceur"],
    ["demorar", "prendre du retard, retarder"],
    ["antojo", "caprice"],
    ["libre albedrío", "le libre arbitre"],
    ["albedrío", "la volonté, will"],
    ["jadear", "haleter"],
    ["empapar", "tremper"],
    ["pocilga", "porcherie"],
    ["delantal", "tablier"],
    ["matarife", "boucher, abatteur"],
    ["aguardiente", "brandy, eau de vie"],
    ["paño", "étoffe, torchon"],
    ["pendejo", "foolish"],
    ["acertijo", "énigme, devinette"],
    ["bravuconada", "bluff"],
    ["talante", "humeur, disposition, esprit"],
    ["rechoncho", "grasouillet, ramassé"],
    ["desdicha", "malheur, misère"],
    ["recado", "course, message"],
    ["pordiosero", "mendiant"],
    ["matón", "brute, voyou"],
    ["cuartel", "caserne"],
    ["lelo", "bêbête, sot"],
    ["tierno", "tendre"],
    ["arrasar", "anéantir, raser"],
    ["saquear", "piller"],
    ["llanto", "larme, pleur"],
    ["diáfano", "limpide, clair"],
    ["delatar", "dénoncer, trahir"],
    ["fogón", "cuisinière, plaque de cuisine"],
    ["garra", "griffe"],
    ["cerrojo", "verrou"],
    ["alborotar", "faire du tapage, agiter"],
    ["zozobra", "angoisse, nervosité"],
    ["aullar", "hurler"],
    ["tener a raya", "tenir à distance"],
    ["pasarse de la raya", "dépasser les bornes"],
    ["raya", "ligne (dans expressions)"],
    ["tranca", "une barre, fig. cuite"],
    ["candado", "cadenas"],
    ["enloquecer", "rendre fou, devenir fou, flipper, craquer"],
    ["estribo", "étrier"],
    ["manar", "couler, suinter"],
    ["témpano", "gros morceau (de glace)"],
    ["punzada", "piqure, élancement (douleur)"],
    ["balde", "seau (esp am.)"],
    ["desvanecerse", "s'évanouir"],
    ["cal", "chaux"],
    ["bramante", "ficelle"],
    ["pesadumbre", "chagrin"],
    ["escurrir", "égoutter"],
    ["restregar", "frotter"],
    ["pisar", "marcher sur, fouler, écraser"],
    ["hacerse amigos", "devenir amis"],
    ["claraboya", "lucarne"],
    ["palangana", "bassine"],
    ["mampostería", "maçonnerie"],
    ["reyerta", "rixe, bagarre"],
    ["baraja", "paquet de cartes (pour jeu)"],
    ["mechón", "mèche"],
    ["palo", "bâton, piquet"],
    ["cornisa", "corniche"],
    ["dicha", "bonheur, félicité"],
    ["empecinado", "obstiné"],
    ["cachivache", "truc, machin, bazar"],
    ["desmigajar", "s'émietter"],
    ["carcacha", "vieille voiture, tacot"],
    ["remendar", "rapiécer, rafistoler"],
    ["retrete", "toilettes, chiottes"],
    ["malograr", "gâcher"],
    ["de remate", "complètement"],
    ["esquela", "notice, faire part"],
    ["comadrona", "sage femme"],
    ["desbaratar", "faire échouer"],
    ["olla", "marmite"],
    ["estanque", "la mare, bassin"],
    ["al cabo de ...", "au bout de ...."],
    ["verosímil", "vraisemblable, réaliste"],
    ["empeño", "acharnement"],
    ["mojigato", "bigot, puribond, prude"],
    ["escarnio", "insulte, raillerie"],
    ["aflojar", "déserrer, détendre"],
    ["abismar", "plonger (dans la douleur, ...)"],
    ["espuela", "éperon"],
    ["desgreñado", "dépeigné"],
    ["ahijado", "filleul"],
    ["carajo!", "merde!"],
    ["desfile", "parade, défilé"],
    ["deslumbrar", "éblouir"],
    ["empellón", "coup"],
    ["acuchillar", "poignarder"],
    ["derrumbarse", "s'écrouler, s'effondrer"],
    ["de bruces", "sur le ventre, face down"],
    ["pauta", "guideline"],
    ["pericia", "expertise, skill, know how"],
    ["abarcar", "englober, inclure"],
    ["arrostrar", "faire face, affronter"],
    ["enfoque", "approche, méthode"],
    ["ya que", "puisque, as "],
    ["hacer falta", "être nécessaire"],
    ["hacer hincapié", "emphasize, mettre l'accent"],
    ["congoja", "chagrin, angoisse"],
    ["trastorno", "trouble, maladie, désordre"],
    ["acierto", "succès"],
    ["perenne", "éternel"],
    ["derrotero", "ligne de conduite"],
    ["merendar", "goûter, pique niquer"],
    ["merienda", "le goûter"],
    ["boticario", "pharmacien"],
    ["vigente", "en vigueur, actuel"],
    ["desempeñar", "exercer "],
    ["propinar", "porter (des coups...)"],
    ["palanca", "levier, manette"],
    ["herejes", "hérésie"],
    ["enojo", "colére, rage"],
    ["traste", "fesse, cul"],
    ["irse al traste", "tourner court"],
    ["estulticia", "stupidité"],
    ["aniquilar", "anéantir"],
    ["lidiar", "traiter, cope with"],
    ["acarrear", "causer, générer"],
    ["vertiente", "une dimension, un aspect"],
    ["prescindir", "faire sans, se passer de, faire abstraction de"],
    ["acopio", "collecte"],
    ["ensayar", "répéter, tester"],
    ["logro", "accomplissement"],
    ["mordaz", "acerbe, mordant"],
    ["codiciar", "convoiter"],
    ["eco", "echo"],
    ["templanza", "modération, maitrise de soi"],
    ["espada", "épée"],
    ["yugo", "joug"],
    ["sin rechistar", "sans rechigner"],
    ["palidecer", "pâlir, blêmir"],
    ["ámbito", "le domaine"],
    ["desentrañar", "unravel, démeler, comprendre"],
    ["borrador", "brouillon, avant-projet"],
    ["tiza", "craie"],
    ["chapucero", "baclé"],
    ["amo", "maître"],
    ["soberano", "souverain"],
    ["hazaña", "exploit"],
    ["azar", "hazard"],
    ["por ende", "donc, par conséquent"],
    ["desalentador", "décourageant, regrettable"],
    ["púlpito", "chaire"],
    ["brindar", "fournir, donner, offrir"],
    ["involucrar", "impliquer, faire participier, to involve"],
    ["amainar", "se calmer, baisser "],
    ["trancar", "caler, verouiller (une porte)"],
    ["seglar", "laïque"],
    ["inconcebible", "impensable"],
    ["al respecto", "à ce sujet"],
    ["en gran medida", "en grande partie"],
    ["en cierta medida", "dans une certaine mesure"],
    ["hacer las veces de", "faire office de"],
    ["arrendar", "louer"],
    ["arriendo", "loyer, location, bail"],
    ["en aras de", "au nom de, au profit de, dans l'interet de"],
    ["aunar", "unir, rassembler (des forces, des efforts)"],
    ["parvulario", "école maternelle"],
    ["ensanchar", "élargir, étendre"],
    ["perfilar", "affiner, esquisser, façonner"],
    ["terco", "têtu, entêté"],
    ["fábula", "fable"],
    ["apañarse", "se débrouiller"],
    ["costear", "financer, payer"],
    ["granjearse a alguien", "gagner l'amitié de"],
    ["idear", "inventer, concevoir, élaborer"],
    ["arrojar", "lancer, jetter"],
    ["zanja", "fossé"],
    ["magro", "maigre, dégraissé"],
    ["por lo tanto", "donc, par conséquent"],
    ["aupar", "porter aux nues, soulever"],
    ["baladí", "futile, sans importance"],
    ["acertar", "atteindre (une cible), réussir"],
    ["el blanco", "la cible"],
    ["acierto", "l'habileté, la réussite"],
    ["contrarrestar", "compenser"],
    ["descartar", "rejetter, exclure, écarter (une option par ex.)"],
    ["seno", "sein"],
    ["sorna", "ironie"],
    ["aguantar", "endurer, supporter"],
    ["a corto plazo", "à court terme"],
    ["desahuciar", "expulser (un locataire)"],
    ["óbito", "décès"],
    ["cantar las cuarenta", "dire ses 4 vérités"],
    ["Entre pitos y flautas", "pour une raison ou une autre, voir exemple"],
    ["carril", "chemin"],
    ["soltura", "facilité, aisance"],
    ["caparazón", "carapace"],
    ["toque de queda", "couvre feu"],
    ["cancerbero", "cerbère, gardien"],
    ["varonil", "viril"],
    ["surtido", "un choix, un assortiment"],
    ["tugurio", "taudis"],
    ["alameda", "allée, peupleraie"],
    ["cascarón", "coquille"],
    ["solaz", "réconfort, confort"],
    ["baratija", "babiolle"],
    ["portazo", "un claqué de porte"],
    ["santo y seña", "mot de passe"],
    ["cañería", "tuyauterie"],
    ["caño", "tuyau"],
    ["pavor", "frayeur, effroi"],
    ["garrotazo", "coup de massue, de gourdin"],
    ["boina", "bérêt"],
    ["teniente", "lieutenant"],
    ["izar", "hisser"],
    ["recluta", "recrue"],
    ["limpiabotas", "cireur de chaussure"],
    ["alardear", "se vanter"],
    ["infundir", "inspirer (la crainte, le respect...)"],
    ["borrar", "gommer, effacer"],
    ["recorrido", "parcours"],
    ["adoquinado", "pavé"],
    ["añoranza", "nostalgie"],
    ["embriaguez", "ivresse"],
    ["resquebrajar", "fissurer"],
    ["rebeldía", "rébellion"],
    ["vedar", "interdire, défendre"],
    ["afincarse", "s'établir"],
    ["apoderarse", "s'aproprier "],
    ["postizo", "faux, postiche"],
    ["manzana", "paté de maison (et fruit)"],
    ["escombro", "décombre, débris"],
    ["en ciernes", "en herbe"],
    ["detener", "arrêter, stopper"],
    ["sequía", "sécheresse"],
    ["al garete", "à la dérive"],
    ["lodo", "boue, vase"],
    ["arrastrar", "trainer"],
    ["gazmoño (south american)", "prude"],
    ["paradero", "endroit"],
    ["azuzar", "exciter, encourager, attiser"],
    ["asomarse", "se pencher en dehors"],
    ["apretón de manos", "poignée de main"],
    ["trastienda", "arrière boutique"],
    ["soñoliento", "somnolent"],
    ["hollín", "suie"],
    ["cobijar", "abriter"],
    ["vitalicio", "à vie"],
    ["arteramente", "insidieusement, astucieusement"],
    ["plantearse", "envisager"],
    ["quebrantar", "violer, enfreindre, ne pas respecter"],
    ["velar por", "veiller à"],
    ["funda", "étui, taie, housse"],
    ["sobaco", "aisselle"],
    ["riña", "querelle"],
    ["yegua", "jument"],
    ["cojera", "claudication, boitement"],
    ["en cuclillas", "accroupi"],
    ["negado para", "pas doué pour"],
    ["conseguir hacer algo", "to manage to do something, réussir à..."],
    ["desazón", "sentiment de malaise, uneasiness"],
    ["regodearse", "jubiler, exulter"],
    ["encajar", "s'intégrer, fit together"],
    ["senda", "sentier, path"],
    ["vorágine", "whirlpool,  maelstrom, tourbillon "],
    ["pecaminoso", "sinful"],
    ["riendas", "rênes"],
    ["barrido", "balayage, coup de balai"],
    ["devolver", "to give back"],
    ["receso", "pause, suspension"],
    ["parto", "accouchement"],
    ["desapego", "détachement, indifférence"],
    ["seto", "haie"],
    ["ejido", "terrain communal"],
    ["arcilla", "argile"],
    ["sarampión", "rougeole"],
    ["pómulo", "pommette, joue"],
    ["gruta", "grotte"],
    ["las afueras", "les environs"],
    ["solapa", "revers (d'une enveloppe, d'un veston), onglet (info)"],
    ["lanzado", "plein d'énergie, direct, horny, impétueux"],
    ["cisne", "cygne"],
    ["granuja", "escroc, canaille"],
    ["palillo", "cure dent"],
    ["añejo", "vielli (le porto)"],
    ["riachuelo", "ruisseau"],
    ["pellizco", "un pincemment, une pincée"],
    ["goteo", "perfusion, goutte à goutte, goutte"],
    ["macizo", "massif (adj), plein"],
    ["hambruna", "famine"],
    ["cacería", "la chasse"],
    ["cabezadita", "petite sieste"],
    ["ocio", "loisirs"],
    ["aprieto", "pétrin"],
    ["hogaza", "loaf, leib, pain"],
    ["enjuto", "sec, mince"],
    ["cuenco", "bol"],
    ["nombre de pila", "prénom"],
    ["airosidad", "grâce, élégance"],
    ["carcajada", "éclat de rire"],
    ["barro", "boue, argile"],
    ["colmado", "rempli, comblé"],
    ["pómulo", "pomette"],
    ["cursi", "ringard, culcul"],
    ["chillón", "bruyant, criard"],
    ["vagar", "errer"],
    ["agujetas", "courbatures"],
    ["proveer", "fournir, offrir"],
    ["alborear", "l'aube"],
    ["plantilla", "le personnel, les salariés"],
    ["desglosar", "break down, répartir"],
    ["prendado de", "épris de, amoureux de"],
    ["papeleo", "paperasserie, les papiers"],
    ["aguardar", "attendre"],
    ["esbozar", "esquisser, décrire"],
    ["puesto que", "puisque"],
    ["candente", "brûlant, torride"],
    ["peliagudo", "délicat (un sujet, ....), difficile"],
    ["mermar", "compromettre, nuire"],
    ["pulcramente", "soigneusement"],
    ["huida", "fuite, évasion"],
    ["sorteo", "lotterie"],
    ["fealdad", "laideur"],
    ["atañer", "concerner, avoir rapport à "],
    ["pifia", "gaffe, bourde"],
    ["en balde", "en vain"],
    ["apegarse", "s'attacher, to become attached to"],
    ["cachorro", "un chiot, plus généralement le petit d'un animal"],
    ["trecho", "un tronçon (d'espace ou de temps), un intervalle"],
    ["menarquía", "l'âge des premières règles (menstruation)"],
    ["despiadado", "impitoyable, sans merci"],
    ["así y todo", "toutefois, mais"],
    ["chiquillo", "gosse, bambin"],
    ["puchero", "marmite, pot au feu"],
    ["cascabel", "petite cloche"],
    ["zueco", "sabot (chaussure)"],
    ["gachas", "flocon d'avoine"],
    ["chitón!", "chut!"],
    ["tosco", "grossier, rudimentaire"],
    ["charol", "vernis (chaussures, cuir)"],
    ["brezal", "la lande, bruyères"],
    ["sensato", "sensé, judicieux"],
["desparpajo", "désinvolture, savoir-faire"],
["me importa un comino", "je m'en fous"],
["comino", "cumin"],
["rociar", "asperger, saupoudrer"],
["sedoso", "soyeux"],
["entrañas", "entrailles"],
["derretirse", "fondre"],
["amigote", "buddy, mate, grand ami"],
["revoltijo", "un fouillis, un bazar, a mess"],
["enrollado", "enroulé"],
["sanseacabó", "un point c'est tout"],
["parrilla", "grill, barbecue"],
["alarido", "cri, hurlement"],
["pezón", "mamelon,téton"],
["vistazo", "coup d'oeil"],
["cántaros", "cruches, fam: tits"],
["mecer", "bercer,balancer"],
["pañal", "couche, lange"],
["tejanos", "jeans (2)"],
["sandía", "pastèque, watermelon"],
["tinglado", "hangar, combine, piège"],
["tiovivo", "manège, carrousel"],
["ojo amoratado", "oeil au beurre noir"],
["santurrón", "bien-pensant, bigot, moralisateur"],
["dar un respingo", "sursauter"],
["foca", "phoque"],
["barandilla", "rampe, balustrade"],
["espeluznante", "très effrayant"],
["ademanes", "manières (gestes et expressions)"],
["reacio", "reluctant, réticent"],
["arcadas", "nausées"],
["holgazán", "paresseux, fainéant"],
["escupir", "cracher"],
["obsequiar", "offrir (par affection)"],
["no te apures", " ne te presse pas"],
["hebra", " brin, mèche"],
["ataviar, ataviado", "habiller, habillé"],
["atisbo", "un soupçon (de qch), une leur (de), une petite quantité (de)"],
["escuálido", "skinny, maigrichon"],
["descansillo", "palier (2)"],
["cordura", "bon sens, raison"],
["nimio", "trivial, insignifiant, futile, sans importance"],
["fármaco", "médicament"],
["mejunje", "mixture,brew"],
["regocijo", "joie,liesse"],
["menguante", "décroissant"],
["escondrijo", "cachette, planque"],
["alijo", "un stock, contrebande"],
["mugriento", "crasseux"],
["pelusa", "peluche,duvet"],
["idóneo (para)", "approprié, idéal, adapté"],
["diosa", "déesse"],
["fardo", "paquet, fardeau"],
["ovillo", "balle, pelote"],
["tufo", "puanteur"],
["abofetear", "gifler, to slap"],
["menear", "remuer, secouer"],
["gorronear", "piquer, taper, voler, to scrounge"],
["mochila", "sac à dos"],
["cucurucho", "un cornet (de frite, de glace)"],
["bobamente", "stupidement"],
["desvaído", "pâle, qui a perdu l'intensité"],
["hada", "fée"],
["¡puñeta", "merde!"],
["alhaja", "bijou, jewel"],
["corcho", "bouchon, liège"],
["sacacorchos", "tire bouchon"],
["tambaleante", "chancelant"],
["apaciguar", "calmer, apaiser"],
["tarado", "idiot, un attardé"],
["mascullar", "marmoner, murmurer"],
["enfurecer", "mettre en colère"],
["anegar", "innonder, noyer"],
["me importa un bledo", "je m'en fiche"],
["a trompicones", "en trébuchant, en titubant"],
["sebo", "graisse, suif"],
["descaradamente", "shamelessly, sans vergogne, ouvertement"],
["tararear", "fredonner"],
["canturrear", "chanter comme un crooner"],
["patada", "coup de pied"],
["escozor", "brûlure, picotement"],
["lío", "lien, liaison (amoureuse aussi)"],
["chasquear", "faire claquer (les doigts, la langue)"],
["desquiciar", "bouleverser, perturber"],
["hueco", "trou, vide"],
["chillido", "cri bruyant et aigu"],
["berrinche", "colère avec pleurs et cris"],
["verdulero", "épicier, marchand de légumes"],
["zancada", "grande enjambée"],
["tembleque", "forts tremblements"],
["vernáculo", "qui est propre du pays (langue, coutume)"],
["lagartija", "lézard"],
["rebosar (de...)", "déborder (de santer, de vie, d'énergie)"],
["telaraña", "cobweb, toile d'areignée"],
["trapicheos", "magouilles"],
["tejemaneje", "intrigue, activité intense"],
["demacrado", "pale, mince et d'un mauvais aspect"],
["piadoso", "pieux, clément, compassif"],
["surcar", "silloner, naviguer"],
["Cuanto más..., más...", " the more, the more"],
["apechugar", "deal with it, go through it, serrer les dents et..."],
["mala pécora", "femme légère, pute"],
["culebrón", "soap opera"],
["bochorno", "embaras, un vent chaud estival"],
["resquicio", "échappatoire, opportunité"],
["lisiado", "infirme, handicapé, crippled"],
["renquear", "boiter, marcher avec difficulté (aussi un business)"],
["hacer ascos", "rejetter quelque chose, faire la fine bouche"],
["cornudo", "cocu"],
["relinchar", "hennir"],
["escampar", "cesser de pleuvoir et le ciel s'éclaircit"],
["bulto", "un voulume de quelque chose, une masse de quelque chose"],
["encía", "gencive"],
["malla", "maillage, grille"]
    ];

    var wordObjects = words.reverse().map(function (x) { return { sp: x[0], tr: x[1], ask: true, status: 1 } });

    var lastExcludedWord = null;
    var lastCurrentWord = null;
    var hasUndoBeenDone = false;

    Array.prototype.randomElement = function () {
        return this[Math.floor(Math.random() * this.length)];
    }

    var wordsToTest = null;   

    var initLastWordList= function(nbSkip, nbTake) {
        wordsToTest = wordObjects.slice(nbSkip, nbSkip + nbTake);
    }

    var getNextWord = function (currentWord) {
        if (hasUndoBeenDone) {
            hasUndoBeenDone = false;
            if (lastCurrentWord) return lastCurrentWord;
        }

        var nextWord = null;
        do {
            nextWord = wordsToTest.randomElement();
        } while (wordsToTest.length > 1 && currentWord === nextWord)
        lastCurrentWord = currentWord;
        return nextWord;
    }

    var excludeWord = function(word) {
        wordsToTest.splice(wordsToTest.indexOf(word), 1);
        lastExcludedWord = word;
    };

    var tryUndoExcludeWord= function() {
        if (lastExcludedWord) {
            wordsToTest.push(lastExcludedWord);
            lastExcludedWord = null;
        }
    }

    wordsServicefactory.undo = function () {
        tryUndoExcludeWord();
        hasUndoBeenDone = true;
    }

    var nbOfWordsToTest = function () {
        return wordsToTest.length;
    }

    wordsServicefactory.nbOfWordsToTest = nbOfWordsToTest;
    wordsServicefactory.excludeWord = excludeWord;
    wordsServicefactory.initLastWordList = initLastWordList;
    wordsServicefactory.getNextWord = getNextWord;

    return wordsServicefactory;
}]);